"""
Django settings for campusflow project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import datetime
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file if it exists
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / ".env")
except Exception:
    pass


# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1", "yes")


# SECURITY WARNING: keep the secret key used in production secret!
# Must be set via the SECRET_KEY env var (see .env). No insecure hardcoded
# fallback is used outside of local DEBUG runs, since this key also signs
# JWTs (SIMPLE_JWT['SIGNING_KEY'] below) — a leaked/known key lets anyone
# forge access tokens for any tenant.
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-local-dev-only-do-not-use-in-production"
    else:
        raise Exception("SECRET_KEY environment variable must be set when DEBUG=False.")

# Symmetric key (Fernet) used to encrypt payment-gateway secrets at rest
# (see campusflow_app/fields.py::EncryptedCharField). Generate one with:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
FIELD_ENCRYPTION_KEY = os.environ.get("FIELD_ENCRYPTION_KEY")
if not FIELD_ENCRYPTION_KEY:
    if DEBUG:
        FIELD_ENCRYPTION_KEY = "BuSMjas03NUbsVS4WDffyQ6JZ3ZZY5h1BGNmX1krWGg="
    else:
        raise Exception("FIELD_ENCRYPTION_KEY environment variable must be set when DEBUG=False.")

# Error tracking — no-op unless SENTRY_DSN is set in .env, so this is safe
# to leave in place for every environment (local dev just won't send
# anything). Wrapped in try/except so a missing sentry-sdk package (not yet
# installed) never breaks startup.
SENTRY_DSN = os.environ.get("SENTRY_DSN")
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            environment=os.environ.get("SENTRY_ENVIRONMENT", "production"),
            # Fraction of requests to trace for performance monitoring — kept
            # low by default since this is a cost-bearing SaaS feature, not
            # free; raise via SENTRY_TRACES_SAMPLE_RATE once on a paid plan.
            traces_sample_rate=float(os.environ.get("SENTRY_TRACES_SAMPLE_RATE", "0.05")),
            send_default_pii=False,
        )
    except ImportError:
        pass

_default_hosts = "campusnexus.in,.campusnexus.in"
ALLOWED_HOSTS = [h for h in os.environ.get("ALLOWED_HOSTS", _default_hosts).split(",") if h]
if DEBUG:
    ALLOWED_HOSTS += ["*"]

CSRF_TRUSTED_ORIGINS = [
    'https://campusnexus.in',
    'https://*.campusnexus.in',
    'http://localhost:5173',
    'http://localhost:5174',
    'http://127.0.0.1:5173',
    'http://127.0.0.1:5174',
]

# Explicit origin allowlist instead of CORS_ALLOW_ALL_ORIGINS — mirrors
# CSRF_TRUSTED_ORIGINS above. Override/extend via the CORS_ALLOWED_ORIGINS
# env var (comma-separated) for local frontend dev servers, e.g.
# "http://localhost:5173,http://localhost:3000".
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
]
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://([a-z0-9-]+\.)?campusnexus\.in$",
]
_extra_cors_origins = [o for o in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",") if o]
if _extra_cors_origins:
    CORS_ALLOWED_ORIGINS.extend(_extra_cors_origins)
if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES.append(r"^http://([a-z0-9-]+\.)?localhost:\d+$")

# django-cors-headers only allows its own default header set unless told
# otherwise — X-Tenant (set by the frontend so CampusFlowTenantMiddleware
# can route to the right schema) isn't in that default list, so it must be
# added explicitly or the browser's CORS preflight rejects it.
from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + ["x-tenant"]

# ============================================================
# TRANSPORT / COOKIE SECURITY
# ============================================================
# Off in DEBUG so local http:// dev isn't broken; the deployed CSRF_TRUSTED_ORIGINS
# above are all https, so these are safe to enforce whenever DEBUG=False.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False  # the frontend JS must be able to read this to set the CSRF header
SECURE_SSL_REDIRECT = not DEBUG
# Let Django know it's behind a reverse proxy terminating SSL, so request.is_secure() returns True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_HSTS_SECONDS = 0 if DEBUG else 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True


# ============================================================
# MULTI-TENANT CONFIGURATION (django-tenants)
# ============================================================

# Tenant & Domain model references
TENANT_MODEL = "tenants.Tenant"
TENANT_DOMAIN_MODEL = "tenants.Domain"

# Apps shared across all tenants (live in the 'public' schema)
SHARED_APPS = [
    "django_tenants",          # mandatory, must be first
    "tenants",                 # where Tenant/Domain models live

    "django.contrib.contenttypes",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "drf_yasg",
    "channels",
]

# Apps that are tenant-specific (each college gets its own tables)
TENANT_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.auth",        # each tenant (college) has its own users
    "django.contrib.admin",
    "rest_framework_simplejwt.token_blacklist",
    "drf_yasg",
    "campusflow_app",
]

# INSTALLED_APPS is the union of SHARED + TENANT (no duplicates)
INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be first for early CORS preflight handling
    'campusflow.middleware.CampusFlowTenantMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'campusflow_app.middleware.audit.AuditMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'campusflow_app.authentication.TenantAwareJWTAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # ...
}

ROOT_URLCONF = "campusflow.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "campusflow.wsgi.application"


# ============================================================
# DATABASE (django-tenants requires its own backend)
# ============================================================

DATABASES = {
    "default": {
        "ENGINE": "django_tenants.postgresql_backend",
        'NAME': os.environ.get('POSTGRES_DB', 'campusflow'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'admin'),
        # Reuse connections across requests instead of opening a fresh TCP+auth
        # handshake every time (default is 0 = no reuse). django-tenants'
        # set_tenant() just issues `SET search_path` on the existing
        # connection when switching schemas, so this is safe to combine with
        # multi-tenancy — the schema switch itself stays cheap.
        # DB_HOST/DB_PORT point at PgBouncer (SESSION pool mode) in
        # docker-compose, not straight at Postgres — see the pgbouncer
        # service comment in docker-compose.yml before changing pool mode.
        # Note: Must be 0 when using PgBouncer to prevent session pool exhaustion.
        'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', 0)),
    }
}

DATABASE_ROUTERS = ('django_tenants.routers.TenantSyncRouter',)


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# ============================================================
# CACHING (OTP & Temporary Data)
# ============================================================
REDIS_URL = os.environ.get('REDIS_URL', None)

if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }


# ============================================================
# DJANGO CHANNELS (WebSocket for Bus Tracking)
# ============================================================
ASGI_APPLICATION = "campusflow.asgi.application"

_redis_url = REDIS_URL or "redis://127.0.0.1:6379/0"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [_redis_url],
        },
    },
}


# ============================================================
# CELERY (offloads CPU-bound face-recognition inference off the
# request/response cycle onto a separately-scalable worker pool —
# see campusflow_app/tasks.py and MarkAttendanceView)
# ============================================================
CELERY_BROKER_URL = _redis_url
CELERY_RESULT_BACKEND = _redis_url
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
# Hard ceiling on how long a single face-pipeline task may run — protects
# against a stuck/misbehaving inference call pinning a worker forever.
CELERY_TASK_TIME_LIMIT = int(os.environ.get("CELERY_TASK_TIME_LIMIT", 20))
# How long MarkAttendanceView blocks waiting for a queued task's result
# before giving up and telling the student to use manual attendance
# instead. Keep below CELERY_TASK_TIME_LIMIT.
FACE_PIPELINE_TASK_TIMEOUT = int(os.environ.get("FACE_PIPELINE_TASK_TIMEOUT", 15))

# ============================================================
# AI-ASSISTED VALUATION (local Ollama vision grading — nothing about a
# scanned paper leaves this machine. See campusflow_app/ai_grading.py and
# the run_ai_grading_suggestion task.
#
# Under docker-compose, Ollama runs as its own service in the same compose
# network (see docker-compose.yml's `ollama` service + entrypoint_ollama.sh,
# which pulls AI_GRADING_MODEL/AI_NARRATIVE_MODEL automatically on boot) —
# the default below is overridden to http://ollama:11434 there. Running
# Django directly on a host instead, point OLLAMA_BASE_URL at wherever
# `ollama serve` is actually running (with AI_GRADING_MODEL/AI_NARRATIVE_MODEL
# pulled beforehand via `ollama pull <model>`).
# ============================================================
OLLAMA_BASE_URL = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
AI_GRADING_MODEL = os.environ.get("AI_GRADING_MODEL", "qwen2.5vl:3b")
# Local CPU vision inference is much slower than a hosted API — generous vs.
# the old Claude timeout on purpose.
AI_GRADING_REQUEST_TIMEOUT_SECONDS = int(os.environ.get("AI_GRADING_REQUEST_TIMEOUT_SECONDS", 240))
# Default Ollama context (2048) is too small once a vision-token image plus
# the rubric/question-structure prompt and JSON-schema output are counted.
AI_GRADING_NUM_CTX = int(os.environ.get("AI_GRADING_NUM_CTX", 8192))
# Scanned answer-sheet images are fetched server-side and capped before
# being base64-encoded and sent to the grading model.
AI_GRADING_MAX_IMAGE_BYTES = int(os.environ.get("AI_GRADING_MAX_IMAGE_BYTES", 10 * 1024 * 1024))

# ============================================================
# ACCREDITATION NARRATIVE DRAFTING (local Ollama text model — see
# campusflow_app/ai_narrative.py and the run_accreditation_narrative_draft
# task). Shares OLLAMA_BASE_URL with AI-assisted valuation above.
# ============================================================
AI_NARRATIVE_MODEL = os.environ.get("AI_NARRATIVE_MODEL", "llama3.2:3b")
AI_NARRATIVE_REQUEST_TIMEOUT_SECONDS = int(os.environ.get("AI_NARRATIVE_REQUEST_TIMEOUT_SECONDS", 180))
AI_NARRATIVE_NUM_CTX = int(os.environ.get("AI_NARRATIVE_NUM_CTX", 8192))

# ============================================================
# TIMETABLE GENERATION (OR-Tools CP-SAT — see
# campusflow_app/services/timetable_generation.py). A fixed, institution-wide
# weekly slot grid for v1, not a per-institution calendar configuration UI.
# ============================================================
TIMETABLE_WORKING_DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
# One hour each, skipping a 13:00 lunch break.
TIMETABLE_SLOT_START_TIMES = [
    datetime.time(hour) for hour in (9, 10, 11, 12, 14, 15, 16)
]
# Hard cap on a single solve — CP-SAT's own search budget, not the Celery
# task's time_limit (which wraps this plus the DB writes with headroom).
TIMETABLE_SOLVER_TIME_LIMIT_SECONDS = int(os.environ.get("TIMETABLE_SOLVER_TIME_LIMIT_SECONDS", 60))


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=7),

    'ROTATE_REFRESH_TOKENS': True,
    # Blacklist old refresh tokens on refresh, so a stolen refresh token
    # can't be replayed after the legitimate user has rotated past it.
    'BLACKLIST_AFTER_ROTATION': True,
    # Keep this False, as we manage session invalidation with our salt
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_LIFETIME': datetime.timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': datetime.timedelta(days=1),

    # This setting is relevant for Simple JWT's internal token handling, not directly our custom salt.
    # Keep it as default unless you have a specific reason to change it.
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
}

# GDAL_LIBRARY_PATH = os.environ.get('GDAL_LIBRARY_PATH')
# GEOS_LIBRARY_PATH = os.environ.get('GEOS_LIBRARY_PATH')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ============================================================
# EMAIL CONFIGURATION (SMTP or Brevo API Backend)
# ============================================================
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")

if EMAIL_HOST:
    DEMO_REAL_EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
    EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"
else:
    DEMO_REAL_EMAIL_BACKEND = "anymail.backends.brevo.EmailBackend"
    ANYMAIL = {
        "BREVO_API_KEY": os.environ.get("BREVO_API_KEY", ""),
    }

# Wraps DEMO_REAL_EMAIL_BACKEND above and silently drops outgoing mail for
# the public demo tenant (see campusflow_app/email_backend.py) — every other
# tenant is unaffected, this just adds one hop before the real backend.
EMAIL_BACKEND = "campusflow_app.email_backend.DemoAwareEmailBackend"

DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "CampusNexus <noreply@campusnexus.in>")

# Recipient list configuration for landing page enquiries
CONTACT_RECIPIENT_EMAIL = os.environ.get("CONTACT_RECIPIENT_EMAIL", "hello@campusnexus.in")
CONTACT_CC_LIST = ["sales@polynexus.in"]
CONTACT_BCC_LIST = ["admin@polynexus.in"]

# ============================================================
# FACE RECOGNITION & BIOMETRICS CONFIGURATION
# ============================================================
FACE_SIMILARITY_THRESHOLD = 0.55
INSIGHTFACE_MODEL_NAME = "buffalo_l"
INSIGHTFACE_MODEL_ROOT = os.environ.get("INSIGHTFACE_MODEL_ROOT", BASE_DIR / "models" / "insightface")

LIVENESS_BLINK_THRESHOLD = 5.5

# ── Adaptive face-template learning ──────────────────────────────────────────
# The ArcFace backbone (buffalo_l) itself is frozen and NOT retrained — instead
# the per-student stored templates are nudged/consolidated over time using
# their own high-confidence verified attendance captures. Real-time EMA gives
# quick, bounded adaptation; the monthly job (fine_tune_face_embeddings command)
# does a robust, outlier-rejecting consolidation once enough samples exist.
FACE_ADAPTIVE_LEARNING_ENABLED = True
FACE_ADAPTIVE_LEARNING_THRESHOLD = 0.75      # only very confident matches may update a template
FACE_ADAPTIVE_LEARNING_MAX_ALPHA = 0.15      # cap on how much a single capture can shift a template
FACE_MONTHLY_FINE_TUNE_MIN_SAMPLES = 6       # min accumulated samples before monthly consolidation runs for a student/angle
FACE_MONTHLY_FINE_TUNE_OUTLIER_FLOOR = 0.50  # samples less similar than this to the running centroid are rejected
FACE_MONTHLY_FINE_TUNE_BLEND_WEIGHT = 0.4    # weight given to the new consolidated centroid vs. the existing template

# The monthly job NEVER writes to the live FaceEmbedding table directly. It stages
# candidate templates as JSON under <root>/<tenant_schema>/<YYYY-MM>/ for manual
# review/testing; `promote_fine_tuned_embeddings` applies them once approved.
FACE_FINE_TUNED_OUTPUT_ROOT = os.environ.get(
    "FACE_FINE_TUNED_OUTPUT_ROOT", str(BASE_DIR / "fine_tuned_embeddings")
)


# try:
#     from .local_settings import *
#     print("Running Development Server....")
# except:
#     print("Running Production Server....")
