# Generated by Django 5.1.7 on 2026-06-17 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusflow_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('user', 'lecture')},
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='main_entry_location',
        ),

        migrations.AddField(
            model_name='attendance',
            name='check_out_time',
            field=models.DateTimeField(blank=True, help_text='Time of checkout (mainly for teaching staff).', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='verification_method',
            field=models.CharField(choices=[('face_geofence', 'Face + Geofence'), ('manual', 'Manual Roll Call')], default='face_geofence', help_text='The method used to verify attendance.', max_length=20),
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='image',
            field=models.ImageField(blank=True, help_text='Registered face image file for this angle.', null=True, upload_to='face_templates/'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_lectures', to='campusflow_app.classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('course', 'classroom', 'day_of_week', 'start_time')},
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('duration_minutes', models.PositiveIntegerField(default=5)),
                ('extended_minutes', models.PositiveIntegerField(default=0)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_meters', models.PositiveIntegerField(default=100)),
                ('tolerance_meters', models.PositiveIntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_session', to='campusflow_app.lecture')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Session',
                'verbose_name_plural': 'Attendance Sessions',
            },
        ),
        migrations.CreateModel(
            name='DeviceResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reason', models.TextField(help_text='Reason for changing their mobile device.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='The admin or staff who approved/rejected this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_device_resets', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_resets', to='campusflow_app.studentprofile')),
            ],
            options={
                'verbose_name': 'Device Reset Request',
                'verbose_name_plural': 'Device Reset Requests',
            },
        ),
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(help_text='Reason for the fraud warning (e.g. Failed Liveness, Spoof Attempt)', max_length=255)),
                ('confidence_score', models.FloatField(help_text='Cosine similarity score during the attempt.')),
                ('captured_image', models.ImageField(blank=True, help_text='Captured frame of the suspicious attempt.', null=True, upload_to='fraud_attempts/')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to='campusflow_app.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to='campusflow_app.studentprofile')),
            ],
            options={
                'verbose_name': 'Fraud Alert',
                'verbose_name_plural': 'Fraud Alerts',
            },
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_type',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='scanned_location',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='classroom_location',
        ),
    ]
