# Generated by Django 5.1.7 on 2026-06-18 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusflow_app', '0002_alter_attendance_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Mid-Term, End Semester', max_length=100)),
                ('code', models.CharField(help_text='Short code, e.g. MID, END, PRAC', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Exam Type',
                'verbose_name_plural': 'Exam Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Casual Leave, Sick Leave', max_length=100)),
                ('code', models.CharField(help_text='Short code, e.g. CL, SL, EL', max_length=10, unique=True)),
                ('max_days', models.PositiveIntegerField(default=12, help_text='Maximum days allowed per academic year.')),
                ('is_paid', models.BooleanField(default=True, help_text='Whether this leave type is paid.')),
                ('applicable_to', models.JSONField(blank=True, default=list, help_text="Roles this leave applies to. e.g. ['Faculty', 'Support Staff']. Empty = all staff.")),
                ('carry_forward', models.BooleanField(default=False, help_text='Whether unused days can be carried to the next academic year.')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Full announcement body text.')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Visual priority level of the announcement.', max_length=10)),
                ('target_roles', models.JSONField(blank=True, default=list, help_text="List of role names this announcement targets. Empty = all roles. e.g. ['student', 'Faculty']")),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned announcements always appear at the top.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-hide announcement after this datetime. Null = never expires.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='The user who created this announcement.', on_delete=django.db.models.deletion.CASCADE, related_name='announcements_authored', to=settings.AUTH_USER_MODEL)),
                ('target_departments', models.ManyToManyField(blank=True, help_text='Departments this announcement targets. Empty = all departments.', related_name='announcements', to='campusflow_app.department')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], help_text='The type of action performed.', max_length=10)),
                ('model_name', models.CharField(help_text="The Django model affected (e.g. 'Lecture', 'LeaveRequest').", max_length=100)),
                ('object_id', models.CharField(blank=True, help_text='Primary key of the affected object.', max_length=50, null=True)),
                ('object_repr', models.CharField(blank=True, help_text='String representation of the object at the time of action.', max_length=500, null=True)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='JSON diff of changes: {field: {old: ..., new: ...}}')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the requester.', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser/device user agent string.', max_length=500, null=True)),
                ('endpoint', models.CharField(blank=True, help_text='The API endpoint that was called.', max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred.')),
                ('user', models.ForeignKey(blank=True, help_text='The user who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. CSE Mid-Term Exam June 2026', max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('passing_marks', models.PositiveIntegerField(default=35)),
                ('semester', models.CharField(blank=True, max_length=50, null=True)),
                ('academic_year', models.CharField(blank=True, help_text='e.g. 2025-2026', max_length=9, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for this exam.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, help_text='Room allocated for this exam.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='campusflow_app.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='campusflow_app.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='campusflow_app.department')),
                ('invigilator', models.ForeignKey(blank=True, help_text='Faculty assigned as invigilator.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilated_exams', to=settings.AUTH_USER_MODEL)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='campusflow_app.examtype')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='First day of leave.')),
                ('end_date', models.DateField(help_text='Last day of leave (inclusive).')),
                ('reason', models.TextField(help_text='Reason for the leave request.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason given if rejected.', null=True)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('reviewed_on', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='The admin/HOD who approved or rejected this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The staff member applying for leave.', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='campusflow_app.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'ordering': ['-applied_on'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=0, help_text='House Rent Allowance', max_digits=12)),
                ('da', models.DecimalField(decimal_places=2, default=0, help_text='Dearness Allowance', max_digits=12)),
                ('ta', models.DecimalField(decimal_places=2, default=0, help_text='Travel Allowance', max_digits=12)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pf_deduction', models.DecimalField(decimal_places=2, default=0, help_text='Provident Fund', max_digits=12)),
                ('esi_deduction', models.DecimalField(decimal_places=2, default=0, help_text='Employee State Insurance', max_digits=12)),
                ('tds_deduction', models.DecimalField(decimal_places=2, default=0, help_text='Tax Deducted at Source', max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The employee this salary structure belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary Structure',
                'verbose_name_plural': 'Salary Structures',
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='Academic year, e.g. 2025-2026', max_length=9)),
                ('allocated', models.PositiveIntegerField(default=0, help_text='Total days allocated.')),
                ('used', models.PositiveIntegerField(default=0, help_text='Days used so far.')),
                ('carried', models.PositiveIntegerField(default=0, help_text='Days carried forward from previous year.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='campusflow_app.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
                'unique_together': {('user', 'leave_type', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(help_text='Month number (1-12)')),
                ('year', models.PositiveIntegerField(help_text='Year, e.g. 2026')),
                ('total_working_days', models.PositiveIntegerField(default=0)),
                ('present_days', models.PositiveIntegerField(default=0)),
                ('leave_days', models.PositiveIntegerField(default=0, help_text='Approved leaves in this month.')),
                ('absent_days', models.PositiveIntegerField(default=0, help_text='Working − Present − Leave')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('absence_deduction', models.DecimalField(decimal_places=2, default=0, help_text='(gross / working_days) × absent_days', max_digits=12)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0, help_text='gross − total_deductions − absence_deduction', max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('paid', 'Paid')], default='draft', max_length=10)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_payslips', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payslip',
                'verbose_name_plural': 'Payslips',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'month', 'year')},
            },
        ),
    ]
