# Generated by Django 5.1.7 on 2026-06-18 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusflow_app', '0003_examtype_leavetype_announcement_auditlog_exam_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the assignment.', max_length=255)),
                ('description', models.TextField(help_text='Detailed description and instructions for the assignment.')),
                ('due_date', models.DateTimeField(help_text='Due date and time for submissions.')),
                ('attachment', models.FileField(blank=True, help_text='Optional instruction document or template.', null=True, upload_to='assignments/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(help_text='Course/subject of the assignment.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='campusflow_app.course')),
                ('created_by', models.ForeignKey(help_text='Faculty member who posted this assignment.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='Department this assignment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='campusflow_app.department')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, help_text="Uploaded file containing student's answers.", null=True, upload_to='assignments/submissions/')),
                ('text_submission', models.TextField(blank=True, help_text='Optional text-based response or notes from student.', null=True)),
                ('grade', models.CharField(blank=True, help_text='Grade or score assigned by the faculty.', max_length=20, null=True)),
                ('feedback', models.TextField(blank=True, help_text='Grading feedback or remarks from the instructor.', null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded')], default='submitted', help_text='Current grading status.', max_length=20)),
                ('assignment', models.ForeignKey(help_text='The assignment this submission belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='campusflow_app.assignment')),
                ('student', models.ForeignKey(help_text='The student who submitted this work.', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignment Submission',
                'verbose_name_plural': 'Assignment Submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
