# Generated by Django 5.1.7 on 2026-06-20 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusflow_app', '0004_assignment_assignmentsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualAttendanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(help_text='Reason student is requesting manual attendance.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_attendance_requests', to='campusflow_app.lecture')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='The lecturer who approved/rejected this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attendance_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_attendance_requests', to='campusflow_app.studentprofile')),
            ],
            options={
                'verbose_name': 'Manual Attendance Request',
                'verbose_name_plural': 'Manual Attendance Requests',
                'db_table': 'manual_attendance_requests',
                'constraints': [models.UniqueConstraint(fields=('student', 'lecture'), name='unique_student_lecture_manual_request')],
            },
        ),
    ]
