# Generated by Django 5.2.15 on 2026-06-30 12:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusflow_app', '0005_manualattendancerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fee Category',
                'verbose_name_plural': 'Fee Categories',
            },
        ),
        migrations.CreateModel(
            name='TenantModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(help_text="Name of the user group (e.g. 'student', 'Faculty', 'Department Head')", max_length=100, unique=True)),
                ('allowed_modules', models.JSONField(blank=True, default=list, help_text="List of modules permitted for this group, e.g. ['attendance', 'exams']")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant Module Permission',
                'verbose_name_plural': 'Tenant Module Permissions',
            },
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Route 1 - Wardha Road', max_length=255)),
                ('stops', models.JSONField(default=list, help_text='List of stops: [{"name": "Stop Name", "lat": 0.0, "lng": 0.0}]')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token for QR code generation. Regenerate to invalidate printed QRs.', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, help_text='The staff user who drives this bus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bus_routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bus Route',
                'verbose_name_plural': 'Bus Routes',
            },
        ),
        migrations.CreateModel(
            name='BusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bus_current_location', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_locations', to='campusflow_app.busroute')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. CS Batch 2026 - Semester 1', max_length=255)),
                ('batch_academic_year', models.CharField(blank=True, help_text='Academic year / batch, e.g. 2025-2026 (optional).', max_length=50, null=True)),
                ('program_enrolled_in', models.CharField(blank=True, help_text='Program code / degree, e.g. B.Tech CS (optional).', max_length=100, null=True)),
                ('current_semester_year', models.CharField(blank=True, help_text='Current Semester / Year, e.g. Semester 1 (optional).', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Department this fee structure applies to (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_structures', to='campusflow_app.department')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
            },
        ),
        migrations.CreateModel(
            name='StudentFeeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_structure', models.ForeignKey(blank=True, help_text='The fee structure this invoice was generated from (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='campusflow_app.feestructure')),
                ('student', models.ForeignKey(help_text='The student to whom this invoice is billed.', on_delete=django.db.models.deletion.CASCADE, related_name='fee_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Fee Invoice',
                'verbose_name_plural': 'Student Fee Invoices',
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('net_banking', 'Net Banking')], default='cash', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, help_text='Reference ID for UPI, Bank Transfer or Card slip.', max_length=100, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('collected_by', models.ForeignKey(blank=True, help_text='Admin/Staff user who collected this fee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='campusflow_app.studentfeeinvoice')),
            ],
            options={
                'verbose_name': 'Fee Payment',
                'verbose_name_plural': 'Fee Payments',
            },
        ),
        migrations.CreateModel(
            name='BusAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(blank=True, help_text='Device fingerprint to prevent proxy scanning', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_attendance', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='campusflow_app.busroute')),
            ],
            options={
                'verbose_name': 'Bus Attendance',
                'verbose_name_plural': 'Bus Attendance',
                'indexes': [models.Index(fields=['user', 'route', 'scanned_at'], name='campusflow__user_id_d5b4b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, help_text='Leave blank for no expiry', null=True)),
                ('boarding_stop', models.CharField(blank=True, help_text='Name of the stop where student boards the bus (e.g. Wardha Road stop)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='e.g. Semester 1 fees paid')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='campusflow_app.busroute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bus Subscription',
                'verbose_name_plural': 'Bus Subscriptions',
                'unique_together': {('user', 'route')},
            },
        ),
        migrations.CreateModel(
            name='BusTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trails', to='campusflow_app.busroute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_trails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='campusflow__user_id_bb0bad_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeeStructureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campusflow_app.feecategory')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='campusflow_app.feestructure')),
            ],
            options={
                'verbose_name': 'Fee Structure Item',
                'verbose_name_plural': 'Fee Structure Items',
                'unique_together': {('fee_structure', 'category')},
            },
        ),
        migrations.CreateModel(
            name='StudentFeeInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campusflow_app.feecategory')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='campusflow_app.studentfeeinvoice')),
            ],
            options={
                'verbose_name': 'Student Fee Invoice Item',
                'verbose_name_plural': 'Student Fee Invoice Items',
                'unique_together': {('invoice', 'category')},
            },
        ),
    ]
