# Generated by Django 5.1.7 on 2026-06-30 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusflow_app", "0006_feecategory_tenantmodulepermission_busroute_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("isbn", models.CharField(max_length=50, unique=True)),
                ("publisher", models.CharField(blank=True, max_length=150, null=True)),
                ("total_copies", models.PositiveIntegerField(default=1)),
                ("available_copies", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "gender_type",
                    models.CharField(
                        choices=[
                            ("Boys", "Boys"),
                            ("Girls", "Girls"),
                            ("Co-ed", "Co-ed"),
                        ],
                        default="Boys",
                        max_length=10,
                    ),
                ),
                ("capacity", models.PositiveIntegerField(default=100)),
                ("address", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="InventoryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Inventory Categories",
            },
        ),
        migrations.CreateModel(
            name="RecruitmentDrive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("job_title", models.CharField(max_length=150)),
                ("job_description", models.TextField(blank=True, null=True)),
                ("eligibility_criteria", models.TextField(blank=True, null=True)),
                (
                    "package_lpa",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="CTC package in Lakhs Per Annum",
                        max_digits=5,
                    ),
                ),
                ("drive_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Upcoming", "Upcoming"),
                            ("Active", "Active"),
                            ("Completed", "Completed"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BookCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Issued", "Issued"),
                            ("Lost", "Lost"),
                        ],
                        default="Available",
                        max_length=20,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copies",
                        to="campusflow_app.book",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issued_date", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField()),
                ("returned_date", models.DateField(blank=True, null=True)),
                (
                    "fine_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Issued", "Issued"),
                            ("Returned", "Returned"),
                            ("Overdue", "Overdue"),
                        ],
                        default="Issued",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book_copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="campusflow_app.bookcopy",
                    ),
                ),
                (
                    "staff_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_book_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_issues",
                        to="campusflow_app.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HostelRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.CharField(max_length=20)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=4, help_text="Number of beds in this room"
                    ),
                ),
                (
                    "rent_per_semester",
                    models.DecimalField(
                        decimal_places=2, default=25000.0, max_digits=10
                    ),
                ),
                ("occupied_beds", models.PositiveIntegerField(default=0)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="campusflow_app.hostel",
                    ),
                ),
            ],
            options={
                "unique_together": {("hostel", "room_number")},
            },
        ),
        migrations.CreateModel(
            name="HostelAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allocated_date", models.DateField(auto_now_add=True)),
                ("vacated_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Allocated", "Allocated"), ("Vacated", "Vacated")],
                        default="Allocated",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostel_allocations",
                        to="campusflow_app.studentprofile",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="campusflow_app.hostelroom",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "unit",
                    models.CharField(
                        default="pieces",
                        help_text="e.g. pieces, liters, boxes",
                        max_length=50,
                    ),
                ),
                (
                    "threshold_level",
                    models.IntegerField(
                        default=5,
                        help_text="Minimum stock level before trigger low-stock alert",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="campusflow_app.inventorycategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("Restock", "Restock"), ("Issue", "Issue")],
                        default="Issue",
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_issues",
                        to="campusflow_app.department",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="campusflow_app.inventoryitem",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restocks",
                        to="campusflow_app.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ValuationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Completed", "Completed")],
                        default="Active",
                        max_length=20,
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valuation_sessions",
                        to="campusflow_app.teachingstaffprofile",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valuation_sessions",
                        to="campusflow_app.exam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScannedPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scanned_file_url",
                    models.CharField(
                        help_text="S3 / storage URL of scanned answer script",
                        max_length=500,
                    ),
                ),
                (
                    "allocated_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Evaluated", "Evaluated")],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scanned_papers",
                        to="campusflow_app.studentprofile",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="papers",
                        to="campusflow_app.valuationsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlacementApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applied_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Applied", "Applied"),
                            ("Shortlisted", "Shortlisted"),
                            ("Interviewing", "Interviewing"),
                            ("Selected", "Selected"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Applied",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placement_applications",
                        to="campusflow_app.studentprofile",
                    ),
                ),
                (
                    "drive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="campusflow_app.recruitmentdrive",
                    ),
                ),
            ],
            options={
                "unique_together": {("drive", "student")},
            },
        ),
    ]
