# Generated by Django 5.2.15 on 2026-07-01 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusflow_app', '0007_book_hostel_inventorycategory_recruitmentdrive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='conductor',
            field=models.ForeignKey(blank=True, help_text='The staff user who acts as conductor on this bus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conductor_bus_routes', to=settings.AUTH_USER_MODEL),
        ),
    ]
