# Generated by Django 5.2.15 on 2026-07-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusflow_app', '0008_busroute_conductor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
