# Generated by Django 5.2.15 on 2026-07-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusflow_app', '0009_alter_attendance_check_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedpaper',
            name='mask_code',
            field=models.CharField(blank=True, help_text='Anonymous code for blind evaluation', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='scannedpaper',
            name='question_scores',
            field=models.JSONField(blank=True, default=dict, help_text="Breakdown of marks by question (e.g. {'Q1': 10, 'Q2': 8})"),
        ),
    ]
