# Generated by Django 5.1.7 on 2026-07-10 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusflow_app", "0010_face_embedding_adaptive_learning"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="question_paper_url",
            field=models.CharField(
                blank=True,
                help_text="S3 / storage URL of the question paper PDF",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="question_structure",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Predefined structure of questions and max marks, e.g. {'Q1': 10, 'Q2': 10}",
            ),
        ),
        migrations.AddField(
            model_name="scannedpaper",
            name="mask_code",
            field=models.CharField(
                blank=True,
                help_text="Anonymous code for blind evaluation",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="scannedpaper",
            name="question_scores",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Breakdown of marks by question (e.g. {'Q1': 10, 'Q2': 8})",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="check_in_time",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="feepayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("upi", "UPI"),
                    ("card", "Card"),
                    ("net_banking", "Net Banking"),
                    ("online", "Online (Payment Gateway)"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BusTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("distance_km", models.FloatField(default=0.0)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trips",
                        to="campusflow_app.busroute",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentGatewayTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("razorpay", "Razorpay"),
                            ("cashfree", "Cashfree"),
                            ("payu", "PayU"),
                            ("phonepe", "PhonePe"),
                            ("paytm", "Paytm"),
                            ("mobikwik", "MobiKwik (Zaakpay)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gateway_order_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gateway_payment_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base amount applied to the invoice.",
                        max_digits=12,
                    ),
                ),
                (
                    "convenience_fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What the payer is actually charged (amount + convenience_fee_amount).",
                        max_digits=12,
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("raw_create_response", models.JSONField(blank=True, default=dict)),
                ("raw_webhook_payload", models.JSONField(blank=True, default=dict)),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gateway_transactions",
                        to="campusflow_app.studentfeeinvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Gateway Transaction",
                "verbose_name_plural": "Payment Gateway Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="feepayment",
            name="gateway_transaction",
            field=models.OneToOneField(
                blank=True,
                help_text="Set when payment_method=online — links back to the gateway transaction that produced this receipt.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fee_payment",
                to="campusflow_app.paymentgatewaytransaction",
            ),
        ),
    ]
