# Generated by Django 5.2.15 on 2026-07-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusflow_app', '0010_scannedpaper_mask_code_scannedpaper_question_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='question_paper_url',
            field=models.CharField(blank=True, help_text='S3 / storage URL of the question paper PDF', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='question_structure',
            field=models.JSONField(blank=True, default=dict, help_text="Predefined structure of questions and max marks, e.g. {'Q1': 10, 'Q2': 10}"),
        ),
    ]
