# Generated by Django 5.2.15 on 2026-07-07 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusflow_app', '0011_exam_question_paper_url_exam_question_structure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('net_banking', 'Net Banking'), ('online', 'Online (Payment Gateway)')], default='cash', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentGatewayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('razorpay', 'Razorpay'), ('cashfree', 'Cashfree'), ('payu', 'PayU'), ('phonepe', 'PhonePe'), ('paytm', 'Paytm'), ('mobikwik', 'MobiKwik (Zaakpay)')], max_length=20)),
                ('gateway_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Base amount applied to the invoice.', max_digits=12)),
                ('convenience_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='What the payer is actually charged (amount + convenience_fee_amount).', max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=20)),
                ('raw_create_response', models.JSONField(blank=True, default=dict)),
                ('raw_webhook_payload', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_transactions', to='campusflow_app.studentfeeinvoice')),
            ],
            options={
                'verbose_name': 'Payment Gateway Transaction',
                'verbose_name_plural': 'Payment Gateway Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='feepayment',
            name='gateway_transaction',
            field=models.OneToOneField(blank=True, help_text='Set when payment_method=online — links back to the gateway transaction that produced this receipt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_payment', to='campusflow_app.paymentgatewaytransaction'),
        ),
    ]
