# Generated by Django 5.1.7 on 2026-07-08 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusflow_app', '0012_alter_feepayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administratorprofile',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='True if privacy notice is accepted.'),
        ),
        migrations.AddField(
            model_name='administratorprofile',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='administratorprofile',
            name='consent_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='departmentheadprofile',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='True if privacy notice is accepted.'),
        ),
        migrations.AddField(
            model_name='departmentheadprofile',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departmentheadprofile',
            name='consent_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='managementprofile',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='True if privacy notice is accepted.'),
        ),
        migrations.AddField(
            model_name='managementprofile',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementprofile',
            name='consent_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='nonteachingstaffprofile',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='True if privacy notice is accepted.'),
        ),
        migrations.AddField(
            model_name='nonteachingstaffprofile',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonteachingstaffprofile',
            name='consent_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='True if privacy notice is accepted.'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='consent_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parent_guardian_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parent_guardian_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teachingstaffprofile',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='True if privacy notice is accepted.'),
        ),
        migrations.AddField(
            model_name='teachingstaffprofile',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachingstaffprofile',
            name='consent_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='BiometricConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_given', models.BooleanField(default=True)),
                ('consent_timestamp', models.DateTimeField(auto_now_add=True)),
                ('consent_version', models.CharField(default='v1.0', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_consents', to='campusflow_app.studentprofile')),
            ],
            options={
                'verbose_name': 'Biometric Consent Log',
                'verbose_name_plural': 'Biometric Consent Logs',
                'db_table': 'biometric_consent_logs',
                'ordering': ['-consent_timestamp'],
            },
        ),
    ]
