# Generated by Django 6.0.6 on 2026-07-14 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Was "0012_studentexamresult" — that migration (and 0009/0010/0011 in
        # this same branch) turned out to be a fully duplicate parallel history
        # of 0009/0010/0011/0012/0014-0015 in the other branch (verified
        # field-for-field identical), created when two branches both ran
        # makemigrations independently off 0008 and were merged in git without
        # reconciling migrations. Those duplicates were deleted; this branch
        # now grafts directly onto the branch that's actually applied to real
        # tenant data, right after it adds the Certificate & License Vault.
        ("campusflow_app", "0016_compliancecertificatetype_compliancecertificate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuardianProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guardian_id",
                    models.CharField(
                        help_text="Unique guardian identifier",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "alternate_phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=20)),
                (
                    "consent_given",
                    models.BooleanField(
                        default=False, help_text="True if privacy notice is accepted."
                    ),
                ),
                ("consent_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "consent_version",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        help_text="Linked children",
                        related_name="guardians",
                        to="campusflow_app.studentprofile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Guardian Profile",
                "verbose_name_plural": "Guardian Profiles",
            },
        ),
    ]
