# Generated by Django 6.0.6 on 2026-07-15 02:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_student_qr_tokens(apps, schema_editor):
    """
    A callable default on a unique field is only evaluated ONCE by the
    schema editor for the ADD COLUMN statement, so every pre-existing row
    would otherwise get the same qr_token and violate the unique
    constraint added in the next step. Give each existing row its own
    random token first.
    """
    StudentProfile = apps.get_model("campusflow_app", "StudentProfile")
    for profile in StudentProfile.objects.all():
        profile.qr_token = uuid.uuid4()
        profile.save(update_fields=["qr_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("campusflow_app", "0013_guardianprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bustrip",
            name="boarded_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bustrip",
            name="expected_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bustrip",
            name="missing_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bustrip",
            name="trip_type",
            field=models.CharField(
                choices=[("pickup", "Morning Pickup"), ("drop", "Evening Drop")],
                default="pickup",
                max_length=10,
            ),
        ),
        # Step 1: add the field nullable/non-unique so existing rows can be
        # populated with distinct values before the unique constraint lands.
        migrations.AddField(
            model_name="studentprofile",
            name="qr_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique token for the student's ID card QR code. Regenerate to invalidate old printed cards.",
                null=True,
            ),
        ),
        # Step 2: give every pre-existing row its own token.
        migrations.RunPython(backfill_student_qr_tokens, migrations.RunPython.noop),
        # Step 3: now safe to enforce uniqueness / not-null.
        migrations.AlterField(
            model_name="studentprofile",
            name="qr_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique token for the student's ID card QR code. Regenerate to invalidate old printed cards.",
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="BusScanEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("board", "Board"), ("alight", "Alight")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("boarded", "Boarded"),
                            ("alighted", "Alighted"),
                            ("wrong_route", "Wrong Route"),
                            ("not_subscribed", "Not Subscribed"),
                            ("already_scanned", "Already Scanned"),
                            ("unreadable", "Unreadable"),
                            ("no_authorized_pickup", "No Authorized Pickup"),
                            ("missing", "Missing · Did Not Board"),
                        ],
                        max_length=25,
                    ),
                ),
                ("stop_name", models.CharField(blank=True, max_length=255)),
                (
                    "raw_code",
                    models.CharField(
                        blank=True,
                        help_text="Whatever code was scanned, for audit trail.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_events",
                        to="campusflow_app.busroute",
                    ),
                ),
                (
                    "scanned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The conductor/driver who performed the scan. Null for system-generated MISSING rows.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_scan_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null when the scanned code could not be resolved to a student (UNREADABLE).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_scan_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_events",
                        to="campusflow_app.bustrip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bus Scan Event",
                "verbose_name_plural": "Bus Scan Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["trip", "direction", "status"],
                        name="campusflow__trip_id_ce7918_idx",
                    ),
                    models.Index(
                        fields=["student", "trip"],
                        name="campusflow__student_6252af_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        help_text="e.g. bus_boarding, bus_alighting, bus_missing, homework, marks_published",
                        max_length=50,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Deep-link payload, e.g. {trip_id, student_id}",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="campusflow__recipie_c5c67c_idx",
                    )
                ],
            },
        ),
    ]
