# Generated by Django 6.0.6 on 2026-07-15 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campusflow_app",
            "0014_bustrip_boarded_count_bustrip_expected_count_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="is_half_day",
            field=models.BooleanField(
                default=False,
                help_text="True if this record was approved as a half-day via an attendance correction request.",
            ),
        ),
        migrations.CreateModel(
            name="AttendanceCorrectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Guardian's explanation for why the absence is disputed."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("half_day", "Half Day"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_correction_requests",
                        to="campusflow_app.lecture",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="The guardian user who filed this dispute.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_corrections_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The teacher/HM who approved/rejected/half-dayed this request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_corrections_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_correction_requests",
                        to="campusflow_app.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Correction Request",
                "verbose_name_plural": "Attendance Correction Requests",
                "db_table": "attendance_correction_requests",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "lecture"),
                        name="unique_student_lecture_correction_request",
                    )
                ],
            },
        ),
    ]
