# Generated by Django 6.0.6 on 2026-07-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusflow_app", "0015_attendance_is_half_day_attendancecorrectionrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="notify_parents",
            field=models.BooleanField(
                default=False,
                help_text="If true, a notification is sent to the guardians of every student in the targeted department(s) when this is created.",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="notify_parents",
            field=models.BooleanField(
                default=False,
                help_text="If true, a notification is sent to the guardians of every student in this assignment's department when created.",
            ),
        ),
    ]
