# Generated by Django 5.2.15 on 2026-08-01 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusflow_app', '0015_faceembedding_sample_count_faceembedding_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('issuing_authority', models.CharField(blank=True, help_text='e.g. UGC, AICTE, State Fire Department', max_length=150, null=True)),
                ('renews_annually', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Compliance Certificate Type',
                'verbose_name_plural': 'Compliance Certificate Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='compliance_certificates/')),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Set for anything with a renewal cycle — powers the expiry-reminder job.', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_compliance_certificates', to=settings.AUTH_USER_MODEL)),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='campusflow_app.compliancecertificatetype')),
            ],
            options={
                'verbose_name': 'Compliance Certificate',
                'verbose_name_plural': 'Compliance Certificates',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
