# Generated by Django 6.0.6 on 2026-07-15 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campusflow_app",
            "0017_exam_results_published_exam_results_published_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            (
                                "app_notifications",
                                "App notifications & academic records",
                            ),
                            ("bus_gps", "Bus GPS tracking & boarding alerts"),
                            ("face_recognition", "Face recognition for attendance"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "requirement",
                    models.CharField(
                        choices=[("required", "Required"), ("opt_in", "Opt-in")],
                        max_length=10,
                    ),
                ),
                ("is_granted", models.BooleanField(default=False)),
                ("granted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The guardian (or admin) who granted this consent.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consents_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="campusflow_app.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Consent",
                "verbose_name_plural": "Student Consents",
                "db_table": "student_consents",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "consent_type"),
                        name="unique_student_consent_type",
                    )
                ],
            },
        ),
    ]
