# Generated by Django 6.0.6 on 2026-07-15 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusflow_app", "0018_studentconsent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_semester_year", models.CharField(max_length=50)),
                ("from_section_division", models.CharField(blank=True, max_length=10)),
                ("from_academic_year", models.CharField(blank=True, max_length=9)),
                ("to_semester_year", models.CharField(max_length=50)),
                ("to_section_division", models.CharField(blank=True, max_length=10)),
                ("to_academic_year", models.CharField(blank=True, max_length=9)),
                (
                    "status",
                    models.CharField(
                        choices=[("applied", "Applied"), ("reverted", "Reverted")],
                        default="applied",
                        max_length=10,
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("reverted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_batches",
                        to="campusflow_app.department",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_batches_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reverted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotion_batches_reverted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion Batch",
                "verbose_name_plural": "Promotion Batches",
                "db_table": "promotion_batches",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="PromotionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("promote", "Promote"),
                            ("hold", "Hold"),
                            ("exclude", "Exclude"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("previous_semester_year", models.CharField(blank=True, max_length=50)),
                (
                    "previous_section_division",
                    models.CharField(blank=True, max_length=10),
                ),
                (
                    "previous_batch_academic_year",
                    models.CharField(blank=True, max_length=9),
                ),
                ("previous_status", models.CharField(blank=True, max_length=20)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="campusflow_app.promotionbatch",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_records",
                        to="campusflow_app.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion Record",
                "verbose_name_plural": "Promotion Records",
                "db_table": "promotion_records",
            },
        ),
    ]
