# Generated by Django 6.0.6 on 2026-07-15 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusflow_app", "0019_promotionbatch_promotionrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentLinkRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "claimed_relationship",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Father, Mother, Guardian",
                        max_length=50,
                    ),
                ),
                ("contact_phone", models.CharField(blank=True, max_length=15)),
                (
                    "phone_mismatch",
                    models.BooleanField(
                        default=False,
                        help_text="True if contact_phone doesn't match any guardian already linked to this student.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("id_requested", "ID Requested"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_note", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_link_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent_link_requests_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_requests",
                        to="campusflow_app.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent Link Request",
                "verbose_name_plural": "Parent Link Requests",
                "db_table": "parent_link_requests",
                "ordering": ["-requested_at"],
            },
        ),
    ]
