# Generated by Django 6.0.6 on 2026-07-26 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusflow_app", "0020_parentlinkrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="paper_finalized",
            field=models.BooleanField(
                default=False,
                help_text="Once true, the composed question paper (ExamQuestion rows) is locked from further edits.",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="paper_finalized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SyllabusTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabus_topics",
                        to="campusflow_app.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Syllabus Topic",
                "verbose_name_plural": "Syllabus Topics",
                "db_table": "syllabus_topics",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("marks", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft-disable instead of delete — past papers keep their snapshot regardless.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_bank",
                        to="campusflow_app.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="campusflow_app.syllabustopic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Question Bank",
                "db_table": "question_bank",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaperBlueprintTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_marks", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blueprint_topics",
                        to="campusflow_app.exam",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blueprint_entries",
                        to="campusflow_app.syllabustopic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paper Blueprint Topic",
                "verbose_name_plural": "Paper Blueprint Topics",
                "db_table": "paper_blueprint_topics",
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_label",
                    models.CharField(
                        help_text="e.g. Q1 — matches Exam.question_structure's key convention.",
                        max_length=10,
                    ),
                ),
                ("question_text_snapshot", models.TextField()),
                ("marks", models.DecimalField(decimal_places=2, max_digits=5)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_questions",
                        to="campusflow_app.exam",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_usages",
                        to="campusflow_app.question",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_questions",
                        to="campusflow_app.syllabustopic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Question",
                "verbose_name_plural": "Exam Questions",
                "db_table": "exam_questions",
                "ordering": ["order"],
            },
        ),
        migrations.AddConstraint(
            model_name="syllabustopic",
            constraint=models.UniqueConstraint(
                fields=("course", "name"), name="unique_course_topic_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="paperblueprinttopic",
            constraint=models.UniqueConstraint(
                fields=("exam", "topic"), name="unique_exam_blueprint_topic"
            ),
        ),
        migrations.AddConstraint(
            model_name="examquestion",
            constraint=models.UniqueConstraint(
                fields=("exam", "question_label"), name="unique_exam_question_label"
            ),
        ),
    ]
