# Generated by Django 6.0.6 on 2026-07-30 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campusflow_app",
            "0021_exam_paper_finalized_exam_paper_finalized_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Canonical form "2025-2026". Used as the display label everywhere.',
                        max_length=9,
                        unique=True,
                    ),
                ),
                ("start_date", models.DateField(help_text="Typically 1 July.")),
                (
                    "end_date",
                    models.DateField(
                        help_text="Typically 30 June of the following year."
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Exactly one AcademicYear may be current; enforced by a partial unique constraint.",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="Set once results are finalised. Closed years reject new terms and exams.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Academic Year",
                "verbose_name_plural": "Academic Years",
                "ordering": ["-start_date"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("is_current",),
                        name="uniq_current_academic_year",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gt", models.F("start_date"))),
                        name="academic_year_end_after_start",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Display name, e.g. "Odd Semester" or "Semester 1".',
                        max_length=50,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("odd", "Odd Semester"),
                            ("even", "Even Semester"),
                            ("summer", "Summer Term"),
                            ("annual", "Annual"),
                            ("trimester", "Trimester"),
                        ],
                        default="odd",
                        max_length=10,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Order within the academic year: 1 for odd/first, 2 for even/second.",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Exactly one Term may be current across all years.",
                    ),
                ),
                (
                    "result_entry_open",
                    models.BooleanField(
                        default=True,
                        help_text="When False, marks entry for exams in this term is closed.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="campusflow_app.academicyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "Term",
                "verbose_name_plural": "Terms",
                "ordering": ["-academic_year__start_date", "sequence"],
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="term",
            field=models.ForeignKey(
                blank=True,
                help_text="Academic term this exam belongs to. Supersedes semester/academic_year.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exams",
                to="campusflow_app.term",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="term",
            field=models.ForeignKey(
                blank=True,
                help_text="Academic term this schedule belongs to. Supersedes semester/academic_year.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedules",
                to="campusflow_app.term",
            ),
        ),
        migrations.AddIndex(
            model_name="term",
            index=models.Index(
                fields=["start_date", "end_date"], name="campusflow__start_d_e317e3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="term",
            constraint=models.UniqueConstraint(
                fields=("academic_year", "sequence"), name="uniq_term_sequence_per_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="term",
            constraint=models.UniqueConstraint(
                fields=("academic_year", "name"), name="uniq_term_name_per_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="term",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("is_current",),
                name="uniq_current_term",
            ),
        ),
        migrations.AddConstraint(
            model_name="term",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gt", models.F("start_date"))),
                name="term_end_after_start",
            ),
        ),
    ]
