# Generated by Django 6.0.6 on 2026-07-30 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusflow_app", "0022_academicyear_term_exam_term_schedule_term_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_year", models.PositiveSmallIntegerField()),
                ("name", models.CharField(help_text="e.g. 2025-2029.", max_length=50)),
                (
                    "expected_graduation_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "current_semester_number",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Curriculum position of the bulk of this batch; advanced by a promotion run.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Batch",
                "verbose_name_plural": "Batches",
                "ordering": ["-admission_year", "program__code"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. A. Capped at 10 to mirror the legacy section_division.",
                        max_length=10,
                    ),
                ),
                (
                    "semester_number",
                    models.PositiveSmallIntegerField(
                        help_text="Curriculum semester this section applies to."
                    ),
                ),
                ("capacity", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "ordering": ["semester_number", "name"],
            },
        ),
        migrations.AddField(
            model_name="course",
            name="canonical_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Regulation-independent identity — CS301 for both 21CS301 and 22CS301 — so trend reporting can follow a course across schemes.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="counts_toward_cgpa",
            field=models.BooleanField(
                default=True,
                help_text="Separate from is_credit_bearing on purpose: some regulations count a course for SGPA but not CGPA, and 0-credit mandatory courses still appear on the transcript as pass/fail.",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("core", "Core"),
                    ("elective_prof", "Professional Elective"),
                    ("elective_open", "Open Elective"),
                    ("lab", "Laboratory"),
                    ("project", "Project"),
                    ("internship", "Internship"),
                    ("mandatory_nc", "Mandatory Non-Credit"),
                    ("value_added", "Value Added"),
                    ("skill", "Skill Enhancement"),
                    ("mooc", "MOOC / SWAYAM"),
                ],
                default="core",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="credits",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="course",
            name="is_credit_bearing",
            field=models.BooleanField(
                default=True,
                help_text="False for audit and mandatory non-credit courses, which are excluded from SGPA.",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="lecture_hours",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="practical_hours",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="semester_number",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Curriculum position 1..N. NOT a calendar term — see Term.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="tutorial_hours",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="academic_year_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fee_structures",
                to="campusflow_app.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="semester_number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="academic_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("detained", "Detained"),
                    ("dropped", "Dropped"),
                    ("graduated", "Graduated"),
                    ("transferred", "Transferred"),
                    ("on_break", "On Break (NEP exit)"),
                ],
                default="active",
                help_text="Academic standing. Distinct from `status`, which is account state.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="current_semester_number",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Curriculum position 1..N. Structured form of current_semester_year.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="campusflow_app.department",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fee_structures",
                to="campusflow_app.batch",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="campusflow_app.batch",
            ),
        ),
        migrations.CreateModel(
            name="GradingScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "max_points",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        help_text="Highest grade point on this scale — 10 for a 10-point scale.",
                        max_digits=4,
                    ),
                ),
                (
                    "passing_grade_points",
                    models.DecimalField(
                        decimal_places=2,
                        default=4,
                        help_text="Minimum grade points that count as a pass.",
                        max_digits=4,
                    ),
                ),
                (
                    "rounding_decimals",
                    models.PositiveSmallIntegerField(
                        default=2, help_text="Decimal places for computed SGPA/CGPA."
                    ),
                ),
                (
                    "is_absolute",
                    models.BooleanField(
                        default=True,
                        help_text="True for fixed percentage bands. False for relative/curve grading.",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="The scheme used when a Regulation names none. At most one may be default.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Grading Scheme",
                "verbose_name_plural": "Grading Schemes",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("is_default",),
                        name="uniq_default_grading_scheme",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GradeBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "letter",
                    models.CharField(
                        help_text="O, A+, A, B+, B, C, P, F, AB, I, W.", max_length=5
                    ),
                ),
                ("min_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("max_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grade_points", models.DecimalField(decimal_places=2, max_digits=4)),
                ("is_pass", models.BooleanField(default=True)),
                (
                    "counts_in_gpa",
                    models.BooleanField(
                        default=True,
                        help_text="False for W (withdrawn) and I (incomplete), which sit outside the average.",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bands",
                        to="campusflow_app.gradingscheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade Band",
                "verbose_name_plural": "Grade Bands",
                "ordering": ["-min_percentage"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code, e.g. BTCSE.", max_length=20
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="Display form, e.g. B.Tech CS. Capped at 50 to fit the legacy StudentProfile.program_enrolled_in column it mirrors during cutover.",
                        max_length=50,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("ug", "Undergraduate"),
                            ("pg", "Postgraduate"),
                            ("diploma", "Diploma"),
                            ("phd", "Doctoral"),
                            ("certificate", "Certificate"),
                        ],
                        default="ug",
                        max_length=15,
                    ),
                ),
                (
                    "duration_years",
                    models.DecimalField(decimal_places=1, default=4, max_digits=3),
                ),
                (
                    "total_terms",
                    models.PositiveSmallIntegerField(
                        default=8,
                        help_text="Number of curriculum semesters, e.g. 8 for a 4-year degree.",
                    ),
                ),
                (
                    "total_credits_required",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                ("nep_multiple_entry_exit", models.BooleanField(default=False)),
                ("aicte_program_code", models.CharField(blank=True, max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programs",
                        to="campusflow_app.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program",
                "verbose_name_plural": "Programs",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="batch",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="campusflow_app.program",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fee_structures",
                to="campusflow_app.program",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="campusflow_app.program",
            ),
        ),
        migrations.CreateModel(
            name="Regulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. R2023 or 2021 Scheme.", max_length=30
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "effective_from_year",
                    models.PositiveSmallIntegerField(
                        help_text="First admission year this scheme applies to."
                    ),
                ),
                (
                    "effective_to_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "min_credits_to_graduate",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "max_backlogs_to_promote",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Drives the suggested promotion decision once promotion reads marks.",
                        null=True,
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Once locked, credits and L-T-P on its courses cannot change. Protects transcripts already issued under this scheme.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grading_scheme",
                    models.ForeignKey(
                        blank=True,
                        help_text="Falls back to the default scheme when unset.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regulations",
                        to="campusflow_app.gradingscheme",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regulations",
                        to="campusflow_app.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regulation",
                "verbose_name_plural": "Regulations",
                "ordering": ["-effective_from_year", "code"],
            },
        ),
        migrations.AddField(
            model_name="batch",
            name="regulation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="campusflow_app.regulation",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="regulation",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for legacy rows created before the curriculum spine existed.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="campusflow_app.regulation",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="regulation",
            field=models.ForeignKey(
                blank=True,
                help_text="Normally inherited from the batch. Set explicitly ONLY for a regulation-transferred student who failed and re-joined under a newer scheme.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="campusflow_app.regulation",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["regulation", "semester_number"],
                name="campusflow__regulat_2ae657_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("regulation", "course_code"),
                name="uniq_course_code_per_regulation",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                condition=models.Q(("regulation__isnull", True)),
                fields=("course_code",),
                name="uniq_legacy_course_code",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="campusflow_app.batch",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentored_sections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="campusflow_app.section",
            ),
        ),
        migrations.AddConstraint(
            model_name="gradeband",
            constraint=models.UniqueConstraint(
                fields=("scheme", "letter"), name="uniq_grade_letter_per_scheme"
            ),
        ),
        migrations.AddConstraint(
            model_name="gradeband",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_percentage__gte", models.F("min_percentage"))),
                name="grade_band_range_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(
                fields=["department", "is_active"],
                name="campusflow__departm_e67041_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="program",
            constraint=models.UniqueConstraint(
                fields=("code",), name="uniq_program_code"
            ),
        ),
        migrations.AddIndex(
            model_name="regulation",
            index=models.Index(
                fields=["program", "status"], name="campusflow__program_90e555_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="regulation",
            constraint=models.UniqueConstraint(
                fields=("program", "code"), name="uniq_regulation_per_program"
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["program", "is_active"], name="campusflow__program_d22359_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="batch",
            constraint=models.UniqueConstraint(
                fields=("program", "admission_year"), name="uniq_batch_per_program_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("batch", "semester_number", "name"),
                name="uniq_section_per_batch_sem",
            ),
        ),
    ]
