# Generated by Django 6.0.6 on 2026-07-30 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusflow_app", "0023_batch_section_course_canonical_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="studentfeeinvoice",
            constraint=models.UniqueConstraint(
                fields=("student", "fee_structure"),
                name="uniq_invoice_per_student_per_structure",
            ),
        ),
    ]
