# Generated by Django 6.0.6 on 2026-07-30 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campusflow_app",
            "0024_studentfeeinvoice_uniq_invoice_per_student_per_structure",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_seats", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "credits_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Rare per-offering deviation from course.credits — leave unset in the normal case.",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offerings",
                        to="campusflow_app.batch",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offerings",
                        to="campusflow_app.course",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_offerings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = open to the whole batch, e.g. an open elective spanning sections.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offerings",
                        to="campusflow_app.section",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offerings",
                        to="campusflow_app.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Offering",
                "verbose_name_plural": "Course Offerings",
            },
        ),
        migrations.CreateModel(
            name="StudentAcademicSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credits_earned",
                    models.DecimalField(decimal_places=1, default=0, max_digits=7),
                ),
                (
                    "credits_required",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=7, null=True
                    ),
                ),
                (
                    "credit_points_earned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=9),
                ),
                (
                    "cgpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("active_backlog_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "highest_semester_cleared",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("last_computed_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_summary",
                        to="campusflow_app.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Academic Summary",
                "verbose_name_plural": "Student Academic Summaries",
            },
        ),
        migrations.CreateModel(
            name="StudentCourseRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("dropped", "Dropped"),
                            ("withdrawn", "Withdrawn"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("detained", "Detained (attendance)"),
                        ],
                        default="registered",
                        max_length=12,
                    ),
                ),
                (
                    "attempt_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("supplementary", "Supplementary"),
                            ("improvement", "Improvement"),
                            ("repeat", "Repeat / Re-registration"),
                        ],
                        default="regular",
                        max_length=15,
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="1 for a first attempt; incremented for a supplementary/repeat re-registration.",
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="campusflow_app.courseoffering",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registrations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_registrations",
                        to="campusflow_app.studentprofile",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="campusflow_app.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Course Registration",
                "verbose_name_plural": "Student Course Registrations",
            },
        ),
        migrations.CreateModel(
            name="CourseGradeAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credits",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Frozen copy of the course's credits at compute time.",
                        max_digits=4,
                    ),
                ),
                (
                    "internal_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "external_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "total_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "max_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="STORED, unlike StudentExamResult.percentage which is a @property and therefore cannot be queried or aggregated in SQL.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("grade_letter", models.CharField(max_length=5)),
                ("grade_points", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "credit_points",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="credits x grade_points, stored so SGPA is a plain SUM/SUM in SQL.",
                        max_digits=7,
                    ),
                ),
                ("is_pass", models.BooleanField(default=False)),
                (
                    "counts_in_gpa",
                    models.BooleanField(
                        default=True,
                        help_text="False when the course is not credit-bearing or the grade band (e.g. W, I) sits outside the average.",
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField(default=1)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("computed", "Computed from exam results"),
                            ("manual", "Manually entered"),
                            ("imported", "Imported from a previous system"),
                        ],
                        default="computed",
                        max_length=10,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "grading_scheme",
                    models.ForeignKey(
                        help_text="FROZEN — which scheme produced grade_letter, regardless of what the Regulation points at later.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="awards",
                        to="campusflow_app.gradingscheme",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_grade_awards",
                        to="campusflow_app.studentprofile",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_grade_awards",
                        to="campusflow_app.term",
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_award",
                        to="campusflow_app.studentcourseregistration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Grade Award",
                "verbose_name_plural": "Course Grade Awards",
            },
        ),
        migrations.CreateModel(
            name="TermGradeSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester_number",
                    models.PositiveSmallIntegerField(
                        help_text="The student's curriculum position for this term, frozen at compute time."
                    ),
                ),
                (
                    "credits_registered",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "credits_earned",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "credit_points_earned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "sgpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("backlog_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "result_status",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("withheld", "Withheld"),
                            ("incomplete", "Incomplete"),
                        ],
                        default="incomplete",
                        max_length=15,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_grade_sheets",
                        to="campusflow_app.studentprofile",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grade_sheets",
                        to="campusflow_app.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Term Grade Sheet",
                "verbose_name_plural": "Term Grade Sheets",
            },
        ),
        migrations.AddIndex(
            model_name="courseoffering",
            index=models.Index(
                fields=["term", "batch"], name="campusflow__term_id_776466_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseoffering",
            index=models.Index(
                fields=["faculty", "term"], name="campusflow__faculty_15bac1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseoffering",
            constraint=models.UniqueConstraint(
                fields=("course", "term", "section"),
                name="uniq_offering_course_term_section",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseoffering",
            constraint=models.UniqueConstraint(
                condition=models.Q(("section__isnull", True)),
                fields=("course", "term", "batch"),
                name="uniq_batchwide_offering",
            ),
        ),
        migrations.AddIndex(
            model_name="studentcourseregistration",
            index=models.Index(
                fields=["term", "student"], name="campusflow__term_id_f7519b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentcourseregistration",
            index=models.Index(
                fields=["offering", "status"], name="campusflow__offerin_66c82c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentcourseregistration",
            constraint=models.UniqueConstraint(
                fields=("student", "offering", "attempt_number"),
                name="uniq_student_offering_attempt",
            ),
        ),
        migrations.AddIndex(
            model_name="coursegradeaward",
            index=models.Index(
                fields=["student", "term"], name="campusflow__student_6a006c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursegradeaward",
            index=models.Index(
                fields=["term", "is_published"], name="campusflow__term_id_5a36f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="termgradesheet",
            index=models.Index(
                fields=["term", "result_status"], name="campusflow__term_id_c1f2de_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="termgradesheet",
            constraint=models.UniqueConstraint(
                fields=("student", "term"), name="uniq_gradesheet_student_term"
            ),
        ),
    ]
