# Generated by Django 6.0.6 on 2026-07-31 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusflow_app", "0025_courseoffering_studentacademicsummary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(help_text='e.g. "CO1".', max_length=10)),
                ("statement", models.TextField()),
                (
                    "bloom_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("remember", "Remember"),
                            ("understand", "Understand"),
                            ("apply", "Apply"),
                            ("analyse", "Analyse"),
                            ("evaluate", "Evaluate"),
                            ("create", "Create"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "target_attainment_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=60,
                        help_text="% a student must score on this CO's tagged questions to count as attained.",
                        max_digits=5,
                    ),
                ),
                (
                    "target_student_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=60,
                        help_text="% of students who must clear the threshold above for class-level attainment.",
                        max_digits=5,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_outcomes",
                        to="campusflow_app.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Outcome",
                "verbose_name_plural": "Course Outcomes",
                "ordering": ["order", "code"],
            },
        ),
        migrations.AddField(
            model_name="examquestion",
            name="course_outcome",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exam_questions",
                to="campusflow_app.courseoutcome",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="course_outcome",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="campusflow_app.courseoutcome",
            ),
        ),
        migrations.AddField(
            model_name="syllabustopic",
            name="course_outcome",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="syllabus_topics",
                to="campusflow_app.courseoutcome",
            ),
        ),
        migrations.CreateModel(
            name="ProgramOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("po", "Programme Outcome"),
                            ("pso", "Programme Specific Outcome"),
                            ("peo", "Programme Educational Objective"),
                        ],
                        default="po",
                        max_length=4,
                    ),
                ),
                (
                    "code",
                    models.CharField(help_text='e.g. "PO1", "PSO2".', max_length=10),
                ),
                ("statement", models.TextField()),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcomes",
                        to="campusflow_app.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Outcome",
                "verbose_name_plural": "Program Outcomes",
                "ordering": ["kind", "order", "code"],
            },
        ),
        migrations.CreateModel(
            name="POCOMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strength",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Low (1)"), (2, "Medium (2)"), (3, "High (3)")],
                        default=1,
                    ),
                ),
                (
                    "course_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="po_mappings",
                        to="campusflow_app.courseoutcome",
                    ),
                ),
                (
                    "program_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="co_mappings",
                        to="campusflow_app.programoutcome",
                    ),
                ),
            ],
            options={
                "verbose_name": "CO-PO Mapping",
                "verbose_name_plural": "CO-PO Mappings",
            },
        ),
        migrations.AddConstraint(
            model_name="courseoutcome",
            constraint=models.UniqueConstraint(
                fields=("course", "code"), name="uniq_course_outcome_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="programoutcome",
            constraint=models.UniqueConstraint(
                fields=("program", "kind", "code"), name="uniq_program_outcome_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="pocomapping",
            constraint=models.UniqueConstraint(
                fields=("course_outcome", "program_outcome"), name="uniq_co_po_pair"
            ),
        ),
    ]
