# Generated by Django 5.2.15 on 2026-08-03 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusflow_app', '0026_courseoutcome_examquestion_course_outcome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Income Category',
                'verbose_name_plural': 'Income Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='compliancecertificatetype',
            name='varies_by_state',
            field=models.BooleanField(default=False, help_text="True for certificates whose issuing body/format is state-specific (Professional Tax, Shops & Establishments, State Pollution Control Board Consent, etc.) rather than a single national body — lets the college's own state stay in issuing_authority."),
        ),
        migrations.CreateModel(
            name='AccreditationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(choices=[('NAAC', 'NAAC'), ('NBA', 'NBA')], default='NAAC', max_length=10)),
                ('code', models.CharField(help_text='e.g. "1.1", "3.4"', max_length=20)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Accreditation Criterion',
                'verbose_name_plural': 'Accreditation Criteria',
                'ordering': ['body', 'code'],
                'constraints': [models.UniqueConstraint(fields=('body', 'code'), name='uniq_accreditation_criterion_code')],
            },
        ),
        migrations.CreateModel(
            name='AuditEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_start', models.DateField()),
                ('access_end', models.DateField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements_granted', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Engagement',
                'verbose_name_plural': 'Audit Engagements',
                'ordering': ['-access_start'],
            },
        ),
        migrations.CreateModel(
            name='AuditorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(blank=True, max_length=255, null=True)),
                ('icai_membership_number', models.CharField(blank=True, help_text='ICAI Membership No. — for engagement letters / audit trail', max_length=20, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditors_invited', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditor Profile',
                'verbose_name_plural': 'Auditor Profiles',
            },
        ),
        migrations.CreateModel(
            name='AuditorAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(help_text="e.g. 'receipts_payments', 'fixed_asset_register'", max_length=50)),
                ('action', models.CharField(choices=[('VIEW', 'View'), ('DOWNLOAD', 'Download')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='campusflow_app.auditengagement')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='campusflow_app.auditorprofile')),
            ],
            options={
                'verbose_name': 'Auditor Access Log',
                'verbose_name_plural': 'Auditor Access Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='auditengagement',
            name='auditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='campusflow_app.auditorprofile'),
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. "2025-2026"', max_length=20, unique=True)),
                ('start_date', models.DateField(help_text='Typically Apr 1.')),
                ('end_date', models.DateField(help_text='Typically Mar 31.')),
                ('opening_cash_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('opening_bank_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_financial_years', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Year',
                'verbose_name_plural': 'Financial Years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('voucher', models.FileField(blank=True, null=True, upload_to='expense_vouchers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='campusflow_app.expensecategory')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_entries', to='campusflow_app.department')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expense_entries', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_entries', to='campusflow_app.supplier')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_entries', to='campusflow_app.financialyear')),
            ],
            options={
                'verbose_name': 'Expense Entry',
                'verbose_name_plural': 'Expense Entries',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='naac_evidence/')),
                ('description', models.TextField(blank=True, null=True)),
                ('linked_object_type', models.CharField(blank=True, help_text='Optional pointer back to a source record instead of a re-upload, e.g. "Exam", "TeachingStaffProfile".', max_length=100, null=True)),
                ('linked_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('signed_off', 'Signed Off')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('signed_off_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='campusflow_app.accreditationcriterion')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accreditation_evidence', to='campusflow_app.department')),
                ('linked_certificate', models.ForeignKey(blank=True, help_text='Reuse a Phase 1 certificate instead of uploading the same PDF a second time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_items', to='campusflow_app.compliancecertificate')),
                ('signed_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_off_evidence', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence_items', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(help_text='Reused as the academic-year anchor for this evidence item.', on_delete=django.db.models.deletion.CASCADE, related_name='accreditation_evidence', to='campusflow_app.financialyear')),
            ],
            options={
                'verbose_name': 'Evidence Item',
                'verbose_name_plural': 'Evidence Items',
                'ordering': ['criterion__code', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='auditengagement',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='campusflow_app.financialyear'),
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(help_text='Furniture, IT Equipment, Vehicle, etc.', max_length=100)),
                ('purchase_date', models.DateField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('depreciation_method', models.CharField(choices=[('SLM', 'Straight Line'), ('WDV', 'Written Down Value')], default='WDV', max_length=20)),
                ('depreciation_rate_percent', models.DecimalField(decimal_places=2, default=15.0, help_text='Admin-editable per asset — Companies Act/IT Act schedule rates are a common starting point, not enforced here.', max_digits=5)),
                ('disposed_date', models.DateField(blank=True, null=True)),
                ('disposal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_assets', to='campusflow_app.department')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_asset_sales', to='campusflow_app.supplier')),
            ],
            options={
                'verbose_name': 'Fixed Asset',
                'verbose_name_plural': 'Fixed Assets',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='IncomeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(blank=True, help_text='Donor name / grant scheme / bank name', max_length=255, null=True)),
                ('received_date', models.DateField()),
                ('receipt_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('voucher', models.FileField(blank=True, null=True, upload_to='income_vouchers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='campusflow_app.incomecategory')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_entries', to='campusflow_app.financialyear')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_income_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Income Entry',
                'verbose_name_plural': 'Income Entries',
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='StateScholarshipScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, help_text='State administering the scheme, blank for a central scheme.', max_length=100, null=True)),
                ('administering_department', models.CharField(blank=True, help_text='e.g. Social Welfare Dept, Directorate of Technical Education', max_length=200, null=True)),
                ('eligible_categories', models.CharField(blank=True, help_text='e.g. SC, ST, OBC, EBC, Minority — free text, comma separated', max_length=255, null=True)),
                ('portal_url', models.URLField(blank=True, help_text="e.g. the state's Mahadbt/e-Kalyan/NSP-style portal, for reference only", max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'State Scholarship Scheme',
                'verbose_name_plural': 'State Scholarship Schemes',
                'ordering': ['state', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'state'), name='uniq_scholarship_scheme_name_state')],
            },
        ),
        migrations.CreateModel(
            name='StudentScholarshipRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('sanctioned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('disbursed_date', models.DateField(blank=True, null=True)),
                ('fee_waiver_applied', models.DecimalField(decimal_places=2, default=0, help_text="How much of the disbursed/sanctioned amount was actually applied as a fee waiver on the student's invoice — kept separate from disbursed_amount because the state portal's payment timeline rarely matches the college's fee due dates.", max_digits=12)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('sanctioned', 'Sanctioned'), ('disbursed', 'Disbursed'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarship_records', to='campusflow_app.financialyear')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_scholarship_records', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='campusflow_app.statescholarshipscheme')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Scholarship Record',
                'verbose_name_plural': 'Student Scholarship Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
