# Generated by Django 5.2.15 on 2026-08-11 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusflow_app', '0027_expensecategory_incomecategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text="Seating capacity. Optional — used by timetable generation to enforce room-fit against a section's size; a classroom with no capacity set skips that check.", null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='answer_key',
            field=models.JSONField(blank=True, default=dict, help_text="Optional per-question model answer / rubric used for AI-assisted grading, e.g. {'Q1': {'max_marks': 10, 'rubric': 'Award full marks if...'}}"),
        ),
        migrations.AddField(
            model_name='scannedpaper',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, help_text='Who last set this paper to Evaluated — manually, or by applying an AI grading suggestion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='course_offering',
            field=models.ForeignKey(blank=True, help_text='Set when this row was produced by (or reconciled against) timetable generation, which schedules against CourseOffering rather than bare Course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='campusflow_app.courseoffering'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='True for a row produced by an unreviewed TimetableGenerationRun. Draft rows are excluded from normal schedule views until the run is applied.'),
        ),
        migrations.AddField(
            model_name='teachingstaffprofile',
            name='max_weekly_teaching_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional cap used by timetable generation to avoid overloading this faculty member; unset = no limit.', null=True),
        ),
        migrations.CreateModel(
            name='AccreditationNarrativeDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('narrative_text', models.TextField(blank=True, help_text='The draft/final SSR write-up — human-editable at any time, before or after apply.')),
                ('caveats', models.TextField(blank=True, help_text="AI-flagged gaps, e.g. 'no evidence found for sub-metric X'.")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrative_drafts', to='campusflow_app.accreditationcriterion')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrative_drafts', to='campusflow_app.financialyear')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accreditation Narrative Draft',
                'verbose_name_plural': 'Accreditation Narrative Drafts',
                'db_table': 'accreditation_narrative_drafts',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AIGradingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('question_scores_suggested', models.JSONField(blank=True, default=dict, help_text="Per-question AI suggestion, e.g. {'Q1': {'score': 8, 'max_marks': 10, 'rationale': '...', 'confidence': 0.82}}")),
                ('overall_confidence', models.FloatField(blank=True, null=True)),
                ('overall_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scanned_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='campusflow_app.scannedpaper')),
            ],
            options={
                'verbose_name': 'AI Grading Suggestion',
                'verbose_name_plural': 'AI Grading Suggestions',
                'db_table': 'ai_grading_suggestions',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('source', models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('walk_in', 'Walk-in'), ('agent', 'Agent/Consultant'), ('event', 'Education Fair/Event'), ('other', 'Other')], default='website', max_length=20)),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry'), ('contacted', 'Contacted'), ('application_submitted', 'Application Submitted'), ('admitted', 'Admitted'), ('enrolled', 'Enrolled'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='inquiry', max_length=25)),
                ('guardian_name', models.CharField(blank=True, max_length=255)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_phone', models.CharField(blank=True, max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('priority_score', models.FloatField(default=0)),
                ('priority_tier', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='cold', max_length=10)),
                ('priority_computed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.TextField(blank=True, help_text='Rejection or withdrawal reason.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('admitted_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('converted_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_lead', to='campusflow_app.studentprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('interested_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='campusflow_app.department')),
                ('interested_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='campusflow_app.program')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'admission_leads',
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('note', 'Note'), ('status_change', 'Status Change')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='campusflow_app.lead')),
            ],
            options={
                'verbose_name': 'Lead Activity',
                'verbose_name_plural': 'Lead Activities',
                'db_table': 'admission_lead_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('risk_score', models.FloatField(help_text='0-100 composite risk score; higher = more at risk.')),
                ('risk_tier', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('attendance_rate', models.FloatField(blank=True, null=True)),
                ('fee_overdue_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('exam_trend_score', models.FloatField(blank=True, null=True)),
                ('assignment_submission_rate', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Human-readable summary of why this student is flagged.')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_score', to='campusflow_app.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Risk Score',
                'verbose_name_plural': 'Student Risk Scores',
                'db_table': 'student_risk_scores',
                'ordering': ['-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='TimetableGenerationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('infeasible', 'Infeasible'), ('failed', 'Failed'), ('applied', 'Applied'), ('discarded', 'Discarded')], default='pending', max_length=20)),
                ('solve_time_seconds', models.FloatField(blank=True, null=True)),
                ('unscheduled_offerings', models.JSONField(blank=True, default=list, help_text="CourseOffering ids the solver couldn't place, set when status is 'infeasible'.")),
                ('error_message', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text="Optional — narrows generation to one department's offerings. Unset = whole term.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='campusflow_app.department')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_generation_runs', to='campusflow_app.term')),
            ],
            options={
                'verbose_name': 'Timetable Generation Run',
                'verbose_name_plural': 'Timetable Generation Runs',
                'db_table': 'timetable_generation_runs',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='generation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_schedules', to='campusflow_app.timetablegenerationrun'),
        ),
    ]
