# Generated by Django 6.0.6 on 2026-08-22 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusflow_app", "0028_classroom_capacity_exam_answer_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="placementapplication",
            name="offered_ctc_lpa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Actual CTC (Lakhs Per Annum) offered to this student once Selected — distinct from RecruitmentDrive.package_lpa, which is only the advertised package. Feeds the NIRF GO median-salary metric, which needs per-student outcomes, not the drive's headline figure.",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="teachingstaffprofile",
            name="has_phd",
            field=models.BooleanField(
                default=False,
                help_text="Structured flag for the NIRF TLR 'faculty with PhD' metric — qualifications above is free text and isn't reliably queryable.",
            ),
        ),
        migrations.CreateModel(
            name="NIRFDataEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nirf_category",
                    models.CharField(
                        help_text='e.g. "Engineering", "Management", "Overall".',
                        max_length=100,
                    ),
                ),
                (
                    "sponsored_research_funding_lakhs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "consultancy_income_lakhs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("patents_filed", models.PositiveIntegerField(default=0)),
                ("patents_granted", models.PositiveIntegerField(default=0)),
                ("publications_count", models.PositiveIntegerField(default=0)),
                (
                    "library_expenditure_lakhs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "students_admitted_higher_studies",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "students_qualified_govt_exams",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="e.g. GATE/UPSC/state PSC qualifiers among the graduating batch.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "financial_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nirf_entries",
                        to="campusflow_app.financialyear",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "NIRF Data Entry",
                "verbose_name_plural": "NIRF Data Entries",
                "ordering": ["-financial_year__start_date", "nirf_category"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("financial_year", "nirf_category"),
                        name="uniq_nirf_entry_year_category",
                    )
                ],
            },
        ),
    ]
