# Generated by Django 6.0.6 on 2026-08-22 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusflow_app", "0029_placementapplication_offered_ctc_lpa_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StatutoryCommittee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "committee_type",
                    models.CharField(
                        choices=[
                            ("anti_ragging", "Anti-Ragging Committee"),
                            ("icc_posh", "Internal Complaints Committee (POSH)"),
                            ("grievance_redressal", "Grievance Redressal Committee"),
                        ],
                        max_length=25,
                    ),
                ),
                ("formed_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="statutory_committees",
                        to="campusflow_app.academicyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statutory Committee",
                "verbose_name_plural": "Statutory Committees",
                "ordering": ["-academic_year__start_date", "committee_type"],
            },
        ),
        migrations.CreateModel(
            name="CommitteeMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_member_name", models.CharField(blank=True, max_length=255)),
                (
                    "external_member_details",
                    models.CharField(
                        blank=True,
                        help_text="e.g. affiliation, for the mandatory external member.",
                        max_length=255,
                    ),
                ),
                (
                    "role_in_committee",
                    models.CharField(
                        help_text='e.g. "Presiding Officer", "Student Representative", "External Member".',
                        max_length=100,
                    ),
                ),
                ("appointed_date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="committee_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="campusflow_app.statutorycommittee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Committee Membership",
                "verbose_name_plural": "Committee Memberships",
            },
        ),
        migrations.CreateModel(
            name="CommitteeMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meeting_date", models.DateField()),
                ("minutes_text", models.TextField(blank=True)),
                ("action_items", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attendees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="meetings_attended",
                        to="campusflow_app.committeemembership",
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="campusflow_app.statutorycommittee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Committee Meeting",
                "verbose_name_plural": "Committee Meetings",
                "ordering": ["-meeting_date"],
            },
        ),
        migrations.CreateModel(
            name="CommitteeComplaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_anonymous", models.BooleanField(default=False)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Verbal harassment", "Ragging — senior batch".',
                        max_length=150,
                    ),
                ),
                ("description", models.TextField()),
                ("filed_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("under_investigation", "Under Investigation"),
                            ("hearing_scheduled", "Hearing Scheduled"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="received",
                        max_length=25,
                    ),
                ),
                ("action_taken", models.TextField(blank=True)),
                ("resolution_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "complainant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nullable for anonymous grievance submissions. POSH does not forbid capturing this — it forbids disclosing it outside the committee, which is enforced by IsCommitteeMember, not by omitting the field.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filed_committee_complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="complaints",
                        to="campusflow_app.statutorycommittee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Committee Complaint",
                "verbose_name_plural": "Committee Complaints",
                "ordering": ["-filed_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="statutorycommittee",
            constraint=models.UniqueConstraint(
                fields=("committee_type", "academic_year"),
                name="uniq_committee_type_per_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="committeemembership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("external_member_name", ""), ("user__isnull", False)),
                    models.Q(
                        ("user__isnull", True),
                        models.Q(("external_member_name", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="committee_member_is_user_xor_external",
            ),
        ),
    ]
