# Generated by Django 6.0.6 on 2026-08-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusflow_app", "0030_statutorycommittee_committeemembership_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scannedpaper",
            name="scanned_file",
            field=models.FileField(
                blank=True,
                help_text="Direct upload through the app — the actual ingestion path for scanned answer scripts.",
                null=True,
                upload_to="scanned_papers/",
            ),
        ),
        migrations.AlterField(
            model_name="scannedpaper",
            name="scanned_file_url",
            field=models.CharField(
                blank=True,
                help_text="External S3 / storage URL, for scans hosted by a third-party scanning vendor.",
                max_length=500,
                null=True,
            ),
        ),
    ]
