# Generated by Django 6.0.6 on 2026-08-23 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusflow_app", "0032_studentinsightsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="ai_generated",
            field=models.BooleanField(
                default=False,
                help_text="Authored by the local drafting model to fill a topic's marks shortfall during paper generation (see ai_question_generation.py), then saved as a real, reusable bank entry. Flagged so a reviewing faculty member can see which questions weren't human-authored before finalizing a paper — the finalize step is the human checkpoint, not a separate approval queue.",
            ),
        ),
        migrations.CreateModel(
            name="PaperSetVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(help_text='e.g. "Set B".', max_length=20)),
                (
                    "questions_snapshot",
                    models.JSONField(
                        default=list,
                        help_text="List of {label, text, marks, topic_name, ai_generated}, in paper order.",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_set_variants",
                        to="campusflow_app.exam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paper Set Variant",
                "verbose_name_plural": "Paper Set Variants",
                "db_table": "paper_set_variants",
                "ordering": ["label"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("exam", "label"), name="unique_exam_paper_set_label"
                    )
                ],
            },
        ),
    ]
