# Generated by Django 6.0.6 on 2026-08-23 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusflow_app", "0033_question_ai_generated_papersetvariant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyllabusCoverageEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("covered", "Covered"),
                        ],
                        default="not_started",
                        max_length=15,
                    ),
                ),
                (
                    "covered_on",
                    models.DateField(
                        blank=True,
                        help_text="Date this topic was actually taught. Set when status moves to in_progress/covered.",
                        null=True,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="e.g. why a topic took longer, or was skipped/deferred.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="syllabus_coverage_entries",
                        to="campusflow_app.lecture",
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabus_coverage_entries",
                        to="campusflow_app.courseoffering",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage_entries",
                        to="campusflow_app.syllabustopic",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="syllabus_coverage_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Syllabus Coverage Entry",
                "verbose_name_plural": "Syllabus Coverage Entries",
                "db_table": "syllabus_coverage_entries",
                "ordering": ["topic__order", "topic__name"],
                "indexes": [
                    models.Index(
                        fields=["offering", "status"],
                        name="syllabus_co_offerin_3e59e2_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("offering", "topic"),
                        name="uniq_offering_topic_coverage",
                    )
                ],
            },
        ),
    ]
