# Generated by Django 6.0.6 on 2026-08-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusflow_app", "0034_syllabuscoverageentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("LOGIN", "Login"),
                    ("LOGIN_FAILED", "Login failed"),
                    ("LOGOUT", "Logout"),
                ],
                help_text="The type of action performed.",
                max_length=15,
            ),
        ),
    ]
