# Generated by Django 5.2.15 on 2026-08-26 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('campusflow_app', '0035_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadence', models.CharField(choices=[('semester_end', 'Every Semester'), ('year_end', 'Every Academic Year')], default='semester_end', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clearance Settings',
                'verbose_name_plural': 'Clearance Settings',
            },
        ),
        migrations.AddField(
            model_name='promotionrecord',
            name='override_reason',
            field=models.TextField(blank=True, help_text='Set when this student was promoted despite an uncleared clearance request.'),
        ),
        migrations.CreateModel(
            name='ClearanceDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('linked_module', models.CharField(choices=[('fees', 'Fees & Accounts'), ('library', 'Library'), ('hostel', 'Hostel'), ('none', 'No linked data (manual review only)')], default='none', help_text='Which existing model to pull reference dues data from for staff review.', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display sequence.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive desks are excluded from new clearance requests but kept for history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsible_group', models.ForeignKey(help_text="Which role acts on this desk's items, e.g. Librarian, Hostel Warden.", on_delete=django.db.models.deletion.PROTECT, related_name='clearance_desks', to='auth.group')),
            ],
            options={
                'verbose_name': 'Clearance Desk',
                'verbose_name_plural': 'Clearance Desks',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClearanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_type', models.CharField(choices=[('periodic', 'Periodic (promotion / exam eligibility)'), ('final_exit', 'Final Exit (Transfer / No-Dues Certificate)')], default='periodic', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('cleared', 'Cleared')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(blank=True, help_text="Set when the tenant's cadence is year_end, or as the final_exit anchor.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_requests', to='campusflow_app.academicyear')),
                ('generated_by', models.ForeignKey(blank=True, help_text='Blank when created by bulk system generation rather than a manual request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_requests_generated', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_requests', to='campusflow_app.studentprofile')),
                ('term', models.ForeignKey(blank=True, help_text="Set when the tenant's cadence is semester_end.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_requests', to='campusflow_app.term')),
            ],
            options={
                'verbose_name': 'Clearance Request',
                'verbose_name_plural': 'Clearance Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClearanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('reference_snapshot', models.JSONField(blank=True, help_text='Dues/status data pulled from the linked module at review time, shown to staff as a reference.', null=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_items_actioned', to=settings.AUTH_USER_MODEL)),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='campusflow_app.clearancedesk')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='campusflow_app.clearancerequest')),
            ],
            options={
                'verbose_name': 'Clearance Item',
                'verbose_name_plural': 'Clearance Items',
                'ordering': ['desk__order'],
            },
        ),
        migrations.AddConstraint(
            model_name='clearancerequest',
            constraint=models.UniqueConstraint(fields=('student', 'cycle_type', 'term', 'academic_year'), name='uniq_clearance_request_per_cycle'),
        ),
        migrations.AddConstraint(
            model_name='clearanceitem',
            constraint=models.UniqueConstraint(fields=('request', 'desk'), name='uniq_clearance_item_per_desk'),
        ),
    ]
