# Generated by Django 5.2.15 on 2026-08-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusflow_app', '0036_clearance_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aishe_code', models.CharField(blank=True, help_text='AISHE institution code — feeds the IIQA submission and the AISHE annual return.', max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institution Profile',
                'verbose_name_plural': 'Institution Profile',
            },
        ),
        migrations.AddField(
            model_name='payslip',
            name='esi_deduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Employee State Insurance for this month, snapshotted from SalaryStructure at generation time.', max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='pf_deduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Provident Fund for this month, snapshotted from SalaryStructure at generation time.', max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='tds_deduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax Deducted at Source for this month, snapshotted from SalaryStructure at generation time.', max_digits=12),
        ),
        migrations.AddField(
            model_name='teachingstaffprofile',
            name='aicte_cadre',
            field=models.CharField(blank=True, choices=[('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor')], help_text='AICTE cadre category, distinct from the free-text designation above — powers the cadre-wise ratio computation.', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='teachingstaffprofile',
            name='aicte_faculty_id',
            field=models.CharField(blank=True, help_text='AICTE-issued Faculty ID, for the annual Extension of Approval filing.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='statutorycommittee',
            name='committee_type',
            field=models.CharField(choices=[('anti_ragging', 'Anti-Ragging Committee'), ('icc_posh', 'Internal Complaints Committee (POSH)'), ('grievance_redressal', 'Grievance Redressal Committee'), ('sc_st_cell', 'SC/ST Cell'), ('obc_cell', 'OBC Cell'), ('minority_cell', 'Minority Cell'), ('womens_cell', "Women's Cell")], max_length=25),
        ),
    ]
