# Generated by Django 5.2.15 on 2026-08-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusflow_app', '0037_phase0_foundational_compliance_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statutorycommittee',
            name='committee_type',
            field=models.CharField(choices=[('anti_ragging', 'Anti-Ragging Committee'), ('icc_posh', 'Internal Complaints Committee (POSH)'), ('grievance_redressal', 'Grievance Redressal Committee'), ('sc_st_cell', 'SC/ST Cell'), ('obc_cell', 'OBC Cell'), ('minority_cell', 'Minority Cell'), ('womens_cell', "Women's Cell"), ('iqac', 'Internal Quality Assurance Cell (IQAC)'), ('academic_council', 'Academic Council'), ('student_council', 'Student Council')], max_length=25),
        ),
    ]
