# Generated by Django 6.0.6 on 2026-08-26 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusflow_app", "0038_statutory_committee_iqac_academic_student_council"),
    ]

    operations = [
        migrations.CreateModel(
            name="AntiRaggingUndertaking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_number", models.CharField(max_length=30, unique=True)),
                (
                    "undertaking_version",
                    models.CharField(default="v1.0", max_length=10),
                ),
                ("student_acknowledged", models.BooleanField(default=False)),
                (
                    "student_acknowledged_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("parent_guardian_name", models.CharField(blank=True, max_length=255)),
                ("parent_acknowledged", models.BooleanField(default=False)),
                ("parent_acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        help_text="One undertaking is required per student per session.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anti_ragging_undertakings",
                        to="campusflow_app.academicyear",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anti_ragging_undertakings",
                        to="campusflow_app.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anti-Ragging Undertaking",
                "verbose_name_plural": "Anti-Ragging Undertakings",
                "db_table": "anti_ragging_undertakings",
                "ordering": ["-academic_year__start_date", "student__student_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "academic_year"),
                        name="uniq_undertaking_per_student_per_year",
                    )
                ],
            },
        ),
    ]
