# Generated by Django 6.0.6 on 2026-08-26 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusflow_app", "0039_anti_ragging_undertaking"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutcomeIndirectSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "survey_type",
                    models.CharField(
                        choices=[
                            ("course_exit", "Course-Exit Survey"),
                            ("programme_exit", "Programme-Exit Survey"),
                            ("employer", "Employer Survey"),
                            ("alumni", "Alumni Survey"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_open", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="indirect_surveys",
                        to="campusflow_app.academicyear",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required for course-exit surveys; must be left blank for the other three programme-level channels.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indirect_surveys",
                        to="campusflow_app.course",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indirect_surveys",
                        to="campusflow_app.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outcome Indirect Survey",
                "verbose_name_plural": "Outcome Indirect Surveys",
                "ordering": ["-academic_year__start_date", "survey_type"],
            },
        ),
        migrations.CreateModel(
            name="OutcomeIndirectSurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "respondent_label",
                    models.CharField(
                        blank=True,
                        help_text="Free text — e.g. an alumni/employer name or an anonymised roll number.",
                        max_length=255,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="1-5 Likert-scale rating of how well this Program Outcome was achieved.",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indirect_survey_responses",
                        to="campusflow_app.programoutcome",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="campusflow_app.outcomeindirectsurvey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outcome Indirect Survey Response",
                "verbose_name_plural": "Outcome Indirect Survey Responses",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="outcomeindirectsurvey",
            constraint=models.UniqueConstraint(
                fields=("program", "course", "academic_year", "survey_type"),
                name="uniq_indirect_survey_per_scope",
            ),
        ),
    ]
