# Generated by Django 6.0.6 on 2026-08-26 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusflow_app", "0040_nba_indirect_attainment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancecertificate",
            name="financial_year",
            field=models.ForeignKey(
                blank=True,
                help_text="Which financial year this certificate covers — lets a renews-annually certificate (e.g. an audited financial statement) be matched to its year without re-deriving that from issued_date. Optional: most certificates (Trust registration, Fire NOC) aren't year-scoped at all.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compliance_certificates",
                to="campusflow_app.financialyear",
            ),
        ),
        migrations.CreateModel(
            name="AccreditationSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("iiqa", "IIQA"),
                            ("dvv_clarification", "DVV Clarification"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "query_text",
                    models.TextField(
                        blank=True,
                        help_text="DVV clarifications only: the query/objection raised by NAAC's DVV team.",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="The IIQA submission content, or the IQAC's clarification response for a DVV query.",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="accreditation_submissions/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("signed_off", "Signed Off"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("signed_off_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "financial_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accreditation_submissions",
                        to="campusflow_app.financialyear",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signed_off_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_off_accreditation_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Accreditation Submission",
                "verbose_name_plural": "Accreditation Submissions",
                "ordering": ["-financial_year__start_date", "submission_type"],
            },
        ),
        migrations.CreateModel(
            name="FacultyResearchOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "output_type",
                    models.CharField(
                        choices=[
                            ("publication", "Publication"),
                            ("grant", "Research Grant"),
                            ("patent", "Patent"),
                        ],
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("journal_or_venue", models.CharField(blank=True, max_length=255)),
                ("is_peer_reviewed", models.BooleanField(default=False)),
                ("doi_or_url", models.CharField(blank=True, max_length=500)),
                ("funding_agency", models.CharField(blank=True, max_length=255)),
                (
                    "grant_amount_lakhs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("patent_number", models.CharField(blank=True, max_length=100)),
                (
                    "patent_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("filed", "Filed"),
                            ("published", "Published"),
                            ("granted", "Granted"),
                        ],
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_outputs",
                        to="campusflow_app.teachingstaffprofile",
                    ),
                ),
                (
                    "financial_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faculty_research_outputs",
                        to="campusflow_app.financialyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faculty Research Output",
                "verbose_name_plural": "Faculty Research Outputs",
                "ordering": ["-financial_year__start_date", "faculty__employee_id"],
            },
        ),
        migrations.CreateModel(
            name="InstitutionalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        help_text='Free text, e.g. "Workshop", "Extension Activity", "Guest Lecture", "Cultural Fest" — NAAC\'s own event categories are numerous and occasionally revised.',
                        max_length=100,
                    ),
                ),
                ("event_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("participants_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Blank for institution-wide events.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="institutional_events",
                        to="campusflow_app.department",
                    ),
                ),
                (
                    "financial_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institutional_events",
                        to="campusflow_app.financialyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institutional Event",
                "verbose_name_plural": "Institutional Events",
                "ordering": ["-event_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_anonymous", models.BooleanField(default=False)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Curriculum", "Faculty", "Infrastructure".',
                        max_length=100,
                    ),
                ),
                ("feedback_text", models.TextField()),
                ("filed_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("under_review", "Under Review"),
                            ("action_taken", "Action Taken"),
                            ("closed", "Closed"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("action_taken", models.TextField(blank=True)),
                ("action_taken_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_feedback",
                        to="campusflow_app.course",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_feedback",
                        to="campusflow_app.department",
                    ),
                ),
                (
                    "financial_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_feedback",
                        to="campusflow_app.financialyear",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nullable for anonymous feedback — same reasoning as CommitteeComplaint.complainant.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_submissions",
                        to="campusflow_app.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Feedback",
                "verbose_name_plural": "Student Feedback",
                "ordering": ["-filed_date"],
            },
        ),
    ]
