# Generated by Django 6.0.6 on 2026-08-27 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusflow_app", "0042_university_exam_administration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprenticeshipContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employer_name",
                    models.CharField(
                        help_text="May differ from the drive's company_name if the apprenticeship is routed through a different legal entity (a common NATS pattern for large employer groups).",
                        max_length=255,
                    ),
                ),
                (
                    "establishment_registration_number",
                    models.CharField(
                        blank=True,
                        help_text="NATS/BOAT-BOPT establishment registration number.",
                        max_length=100,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "monthly_stipend_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "proof_of_employment",
                    models.FileField(
                        blank=True, null=True, upload_to="apprenticeship_contracts/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "placement_application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apprenticeship_contract",
                        to="campusflow_app.placementapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apprenticeship Contract",
                "verbose_name_plural": "Apprenticeship Contracts",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="StipendClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveSmallIntegerField(help_text="1-12.")),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "claimed_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "attendance_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Employer-reported attendance for this month — self-declared at claim time, since apprentice attendance is tracked by the employer, not this system's own Attendance model.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stipend_claims",
                        to="campusflow_app.apprenticeshipcontract",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stipend_claims_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stipend Claim",
                "verbose_name_plural": "Stipend Claims",
                "ordering": ["-year", "-month"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contract", "month", "year"),
                        name="uniq_stipend_claim_per_month",
                    )
                ],
            },
        ),
    ]
