# Generated by Django 6.0.6 on 2026-08-27 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusflow_app", "0043_nats_apprenticeship_layer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeRegulatingAuthoritySubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proposed_fee_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("revision_requested", "Revision Requested"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "fra_order_number",
                    models.CharField(
                        blank=True,
                        help_text="The FRA's own order/reference number, recorded once decided.",
                        max_length=100,
                    ),
                ),
                (
                    "sanctioned_fee_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The FRA-approved figure once decided — may differ from proposed_fee_amount.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fra_submissions",
                        to="campusflow_app.academicyear",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fee_structure",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to the internal fee structure this proposal corresponds to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fra_submissions",
                        to="campusflow_app.feestructure",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fra_submissions",
                        to="campusflow_app.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fee Regulating Authority Submission",
                "verbose_name_plural": "Fee Regulating Authority Submissions",
                "ordering": ["-academic_year__start_date", "program__code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("program", "academic_year"),
                        name="uniq_fra_submission_per_program_per_year",
                    )
                ],
            },
        ),
    ]
