# Generated by Django 6.0.6 on 2026-08-27 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusflow_app", "0044_fee_regulating_authority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="apaar_id",
            field=models.CharField(
                blank=True,
                help_text="APAAR ID (Automated Permanent Academic Account Registry) — the student's ABC (Academic Bank of Credits) account identifier. Blank until issued by the government; nothing in this system generates one.",
                max_length=12,
                null=True,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="CAPApplicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_number",
                    models.CharField(
                        help_text="State CAP application/form number.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=15)),
                (
                    "cet_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "cet_percentile",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("open", "Open (General)"),
                            ("sc", "SC"),
                            ("st", "ST"),
                            ("vjnt_a", "VJ(A)"),
                            ("nt_b", "NT(B)"),
                            ("nt_c", "NT(C)"),
                            ("nt_d", "NT(D)"),
                            ("obc", "OBC"),
                            ("sbc", "SBC"),
                            ("ews", "EWS"),
                            ("tfws", "TFWS (Tuition Fee Waiver Scheme)"),
                            ("pwd", "PWD"),
                            ("defense", "Defense"),
                            ("minority", "Minority"),
                            ("management", "Management Quota"),
                            ("all_india", "All India (AI)"),
                        ],
                        help_text="The candidate's own reservation category, matched against SeatMatrix.quota_category.",
                        max_length=20,
                    ),
                ),
                ("guardian_name", models.CharField(blank=True, max_length=255)),
                ("guardian_email", models.EmailField(blank=True, max_length=254)),
                ("guardian_phone", models.CharField(blank=True, max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link back to a CRM Lead, if this person was also tracked there.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cap_applicant",
                        to="campusflow_app.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "CAP Applicant",
                "verbose_name_plural": "CAP Applicants",
                "ordering": ["-cet_percentile"],
            },
        ),
        migrations.CreateModel(
            name="CAPRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.PositiveSmallIntegerField()),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "CAP Round 1", "Institute Level Round".',
                        max_length=100,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cap_rounds",
                        to="campusflow_app.academicyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "CAP Round",
                "verbose_name_plural": "CAP Rounds",
                "ordering": ["academic_year__start_date", "round_number"],
            },
        ),
        migrations.CreateModel(
            name="CAPAllotment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quota_category",
                    models.CharField(
                        choices=[
                            ("open", "Open (General)"),
                            ("sc", "SC"),
                            ("st", "ST"),
                            ("vjnt_a", "VJ(A)"),
                            ("nt_b", "NT(B)"),
                            ("nt_c", "NT(C)"),
                            ("nt_d", "NT(D)"),
                            ("obc", "OBC"),
                            ("sbc", "SBC"),
                            ("ews", "EWS"),
                            ("tfws", "TFWS (Tuition Fee Waiver Scheme)"),
                            ("pwd", "PWD"),
                            ("defense", "Defense"),
                            ("minority", "Minority"),
                            ("management", "Management Quota"),
                            ("all_india", "All India (AI)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("allotted", "Allotted"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="allotted",
                        max_length=15,
                    ),
                ),
                ("allotted_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "converted_student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="from_cap_allotment",
                        to="campusflow_app.studentprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cap_allotments",
                        to="campusflow_app.program",
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allotments",
                        to="campusflow_app.capapplicant",
                    ),
                ),
                (
                    "cap_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allotments",
                        to="campusflow_app.capround",
                    ),
                ),
            ],
            options={
                "verbose_name": "CAP Allotment",
                "verbose_name_plural": "CAP Allotments",
                "ordering": ["-allotted_at"],
            },
        ),
        migrations.CreateModel(
            name="FacultyWorkloadStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teaching_hours_per_week",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "courses_taught",
                    models.TextField(
                        blank=True,
                        help_text='Free text summary, e.g. "CS301 Data Structures, CS402 Algorithms".',
                    ),
                ),
                (
                    "administrative_hours_per_week",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload_statements",
                        to="campusflow_app.academicyear",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload_statements",
                        to="campusflow_app.teachingstaffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faculty Workload Statement",
                "verbose_name_plural": "Faculty Workload Statements",
                "ordering": ["-academic_year__start_date", "faculty__employee_id"],
            },
        ),
        migrations.CreateModel(
            name="ReservationRosterEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_designation",
                    models.CharField(
                        help_text='e.g. "Assistant Professor".', max_length=100
                    ),
                ),
                (
                    "roster_point_number",
                    models.PositiveSmallIntegerField(
                        help_text="This post's sequence number in the roster cycle."
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ur", "Unreserved (UR)"),
                            ("sc", "SC"),
                            ("st", "ST"),
                            ("obc", "OBC"),
                            ("ews", "EWS"),
                            ("pwd", "PWD"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_filled", models.BooleanField(default=False)),
                ("filled_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_roster_entries",
                        to="campusflow_app.department",
                    ),
                ),
                (
                    "filled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="campusflow_app.teachingstaffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservation Roster Entry",
                "verbose_name_plural": "Reservation Roster Entries",
                "ordering": [
                    "department__name",
                    "post_designation",
                    "roster_point_number",
                ],
            },
        ),
        migrations.CreateModel(
            name="SeatMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quota_category",
                    models.CharField(
                        choices=[
                            ("open", "Open (General)"),
                            ("sc", "SC"),
                            ("st", "ST"),
                            ("vjnt_a", "VJ(A)"),
                            ("nt_b", "NT(B)"),
                            ("nt_c", "NT(C)"),
                            ("nt_d", "NT(D)"),
                            ("obc", "OBC"),
                            ("sbc", "SBC"),
                            ("ews", "EWS"),
                            ("tfws", "TFWS (Tuition Fee Waiver Scheme)"),
                            ("pwd", "PWD"),
                            ("defense", "Defense"),
                            ("minority", "Minority"),
                            ("management", "Management Quota"),
                            ("all_india", "All India (AI)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_seats", models.PositiveIntegerField()),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_matrix_entries",
                        to="campusflow_app.academicyear",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_matrix_entries",
                        to="campusflow_app.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seat Matrix Entry",
                "verbose_name_plural": "Seat Matrix Entries",
                "ordering": ["program__code", "quota_category"],
            },
        ),
        migrations.CreateModel(
            name="TeacherApprovalProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation_applied_for",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "university_approval_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("remarks", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_approval_proposals",
                        to="campusflow_app.academicyear",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_proposals",
                        to="campusflow_app.teachingstaffprofile",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        help_text="Blank for a department-wide approval not tied to one program.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_approval_proposals",
                        to="campusflow_app.program",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Approval Proposal",
                "verbose_name_plural": "Teacher Approval Proposals",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="ABCCreditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credits_earned", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grade", models.CharField(blank=True, max_length=5)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("synced", "Synced"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abc_credit_entries",
                        to="campusflow_app.academicyear",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abc_credit_entries",
                        to="campusflow_app.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abc_credit_entries",
                        to="campusflow_app.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "ABC Credit Entry",
                "verbose_name_plural": "ABC Credit Entries",
                "ordering": ["-academic_year__start_date", "student__student_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "course", "academic_year"),
                        name="uniq_abc_credit_entry",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AffiliationApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("lic_visit_scheduled", "LIC Visit Scheduled"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=25,
                    ),
                ),
                (
                    "university_reference_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("lic_visit_date", models.DateField(blank=True, null=True)),
                ("lic_committee_members", models.TextField(blank=True)),
                ("lic_observations", models.TextField(blank=True)),
                (
                    "lic_compliance_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("compliant", "Compliant"),
                            ("conditional", "Conditional"),
                            ("non_compliant", "Non-Compliant"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "lic_report_file",
                    models.FileField(
                        blank=True, null=True, upload_to="affiliation_lic_reports/"
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliation_applications",
                        to="campusflow_app.academicyear",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliation_applications",
                        to="campusflow_app.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affiliation Application",
                "verbose_name_plural": "Affiliation Applications",
                "ordering": ["-academic_year__start_date", "program__code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("program", "academic_year"),
                        name="uniq_affiliation_application_per_program_per_year",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="capround",
            constraint=models.UniqueConstraint(
                fields=("academic_year", "round_number"), name="uniq_cap_round_per_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="capallotment",
            constraint=models.UniqueConstraint(
                fields=("applicant", "cap_round"), name="uniq_cap_allotment_per_round"
            ),
        ),
        migrations.AddConstraint(
            model_name="facultyworkloadstatement",
            constraint=models.UniqueConstraint(
                fields=("faculty", "academic_year"),
                name="uniq_workload_statement_per_faculty_per_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservationrosterentry",
            constraint=models.UniqueConstraint(
                fields=("department", "post_designation", "roster_point_number"),
                name="uniq_roster_point_per_post",
            ),
        ),
        migrations.AddConstraint(
            model_name="seatmatrix",
            constraint=models.UniqueConstraint(
                fields=("program", "academic_year", "quota_category"),
                name="uniq_seat_matrix_entry",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherapprovalproposal",
            constraint=models.UniqueConstraint(
                fields=("faculty", "academic_year"),
                name="uniq_teacher_approval_per_faculty_per_year",
            ),
        ),
    ]
