# Generated by Django 5.2.17 on 2026-09-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusflow_app', '0045_state_portal_and_abc_modeling'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='boundary',
            field=models.JSONField(blank=True, help_text="Classroom boundary as a list of [lat, lng] corners, e.g. the room's four corners.", null=True),
        ),
    ]
