# Generated by Django 6.0.6 on 2026-09-29 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_principal_group(apps, schema_editor):
    # Runs once per tenant schema, so every existing college gets the role
    # (new colleges get it from tenants/serializers.py at creation time).
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="Principal")


class Migration(migrations.Migration):

    dependencies = [
        ("campusflow_app", "0046_classroom_boundary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrincipalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Unique employee identifier for the principal",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "aadhaar_number",
                    models.CharField(
                        blank=True,
                        help_text="Unique Aadhaar across all users",
                        max_length=12,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "current_address_line1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "current_district",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "current_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "current_pincode",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "permanent_address_line1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "permanent_address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "permanent_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "permanent_district",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "permanent_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "permanent_pincode",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("date_of_joining", models.DateField(blank=True, null=True)),
                (
                    "designation",
                    models.CharField(
                        blank=True, default="Principal", max_length=100, null=True
                    ),
                ),
                ("employee_type", models.CharField(default="full_time", max_length=20)),
                (
                    "bank_account_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "pan_number",
                    models.CharField(
                        blank=True,
                        help_text="Unique PAN across all users",
                        max_length=10,
                        null=True,
                        unique=True,
                    ),
                ),
                ("staff_role", models.CharField(default="principal", max_length=50)),
                ("status", models.CharField(default="active", max_length=20)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pics/principal/"
                    ),
                ),
                ("assigned_responsibilities", models.TextField(blank=True, null=True)),
                (
                    "office_location_details",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "consent_given",
                    models.BooleanField(
                        default=False, help_text="True if privacy notice is accepted."
                    ),
                ),
                ("consent_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "consent_version",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="principal_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Principal Profile",
                "verbose_name_plural": "Principal Profiles",
            },
        ),
        migrations.RunPython(create_principal_group, migrations.RunPython.noop),
    ]
