services:
  web:
    build: .
    ports:
      - "8200:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    command: /bin/bash ./entrypoint.sh

  db:
    image: postgres:17
    env_file:
      - .env
    volumes:
      - CampusFlow_postgres_data:/var/lib/postgresql/data

volumes:
  CampusFlow_postgres_data:
