# Generated by Django 5.1.7 on 2026-05-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='permitted_email_domain',
            field=models.CharField(blank=True, help_text='e.g. mit.edu.in. If set, students must register with this domain.', max_length=100, null=True),
        ),
    ]
