# Generated by Django 5.1.7 on 2026-06-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_permitted_email_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='email_smtp_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_smtp_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_smtp_port',
            field=models.IntegerField(blank=True, default=587, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_smtp_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='erp_api_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='erp_auth_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='erp_system_name',
            field=models.CharField(blank=True, help_text='e.g. SAP, Banner, Custom ERP', max_length=100, null=True),
        ),
    ]
