# Generated by Django 5.1.7 on 2026-06-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_email_smtp_host_tenant_email_smtp_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='billing_employee_discount',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='billing_employee_rate',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='billing_student_discount',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='billing_student_rate',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
