# Generated by Django 5.1.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_billing_employee_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', help_text='e.g. Asia/Kolkata', max_length=100),
        ),
    ]
