# Generated by Django 5.2.15 on 2026-06-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='subscribed_modules',
            field=models.JSONField(blank=True, default=list, help_text="List of modules subscribed by this college, e.g. ['attendance', 'exams', 'fees']"),
        ),
    ]
