# Generated by Django 5.1.7 on 2026-06-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_tenant_subscribed_modules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="subscribed_modules",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Modules subscribed by this tenant (e.g. ['Hostel', 'TPO', 'Library', 'Inventory', 'Valuation', 'Leave', 'Payroll', 'Exams', 'Assignments', 'Attendance', 'Announcements'])",
            ),
        ),
    ]
