# Generated by Django 5.2.15 on 2026-07-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='cashfree_app_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='cashfree_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='fee_surcharge_mode',
            field=models.CharField(choices=[('absorb', 'Absorb fees (College pays transaction cost)'), ('pass_to_student', 'Pass surcharge to student (Student pays convenience fee)')], default='absorb', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='negotiated_education_rates',
            field=models.BooleanField(default=False, help_text='Enable negotiated education rates (e.g. ~0% UPI MDR/platform fees for colleges)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='payment_gateway_active',
            field=models.CharField(choices=[('manual', 'Manual (Offline / Cash)'), ('razorpay', 'Razorpay'), ('cashfree', 'Cashfree'), ('payu', 'PayU')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='payu_merchant_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='payu_merchant_salt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='razorpay_key_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='razorpay_key_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
