# Generated by Django 5.2.15 on 2026-07-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_tenant_cashfree_app_id_tenant_cashfree_secret_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='mobikwik_merchant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mobikwik_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='paytm_merchant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='paytm_merchant_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phonepe_merchant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phonepe_salt_index',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phonepe_salt_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='payment_gateway_active',
            field=models.CharField(choices=[('manual', 'Manual (Offline / Cash)'), ('razorpay', 'Razorpay'), ('cashfree', 'Cashfree'), ('payu', 'PayU'), ('phonepe', 'PhonePe'), ('paytm', 'Paytm'), ('mobikwik', 'MobiKwik (Zaakpay)')], default='manual', max_length=20),
        ),
    ]
