# Generated by Django 5.1.7 on 2026-07-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0009_tenant_billing_cycle_tenant_subscription_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="bank_receipt",
            field=models.FileField(
                blank=True, null=True, upload_to="billing_receipts/"
            ),
        ),
    ]
