# Generated by Django 5.1.7 on 2026-07-10 13:40

import campusflow_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0010_alter_invoice_bank_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="cashfree_app_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="cashfree_secret_key",
            field=campusflow_app.fields.EncryptedCharField(
                blank=True, max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="convenience_fee_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentage charged to the payer on top of the fee amount when fee_surcharge_mode=pass_to_student.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="fee_surcharge_mode",
            field=models.CharField(
                choices=[
                    ("absorb", "Absorb fees (College pays transaction cost)"),
                    (
                        "pass_to_student",
                        "Pass surcharge to student (Student pays convenience fee)",
                    ),
                ],
                default="absorb",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="is_demo",
            field=models.BooleanField(
                default=False,
                help_text="Public sandbox tenant — password changes, email changes, outgoing mail, and destructive/config actions are blocked for every user in this tenant so a shared public demo can't be broken or hijacked.",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="mobikwik_merchant_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="mobikwik_secret_key",
            field=campusflow_app.fields.EncryptedCharField(
                blank=True, max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="negotiated_education_rates",
            field=models.BooleanField(
                default=False,
                help_text="Enable negotiated education rates (e.g. ~0% UPI MDR/platform fees for colleges)",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="payment_gateway_active",
            field=models.CharField(
                choices=[
                    ("manual", "Manual (Offline / Cash)"),
                    ("razorpay", "Razorpay"),
                    ("cashfree", "Cashfree"),
                    ("payu", "PayU"),
                    ("phonepe", "PhonePe"),
                    ("paytm", "Paytm"),
                    ("mobikwik", "MobiKwik (Zaakpay)"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="paytm_merchant_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="paytm_merchant_key",
            field=campusflow_app.fields.EncryptedCharField(
                blank=True, max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="payu_merchant_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="payu_merchant_salt",
            field=campusflow_app.fields.EncryptedCharField(
                blank=True, max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="phonepe_merchant_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="phonepe_salt_index",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="phonepe_salt_key",
            field=campusflow_app.fields.EncryptedCharField(
                blank=True, max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="razorpay_key_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="razorpay_key_secret",
            field=campusflow_app.fields.EncryptedCharField(
                blank=True, max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="razorpay_webhook_secret",
            field=campusflow_app.fields.EncryptedCharField(
                blank=True,
                help_text="Secret configured in the Razorpay dashboard's Webhooks section, used to verify webhook signatures.",
                max_length=500,
                null=True,
            ),
        ),
    ]
