# Generated by Django 5.2.15 on 2026-07-07 13:02

import campusflow_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenant_mobikwik_merchant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='convenience_fee_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage charged to the payer on top of the fee amount when fee_surcharge_mode=pass_to_student.', max_digits=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='razorpay_webhook_secret',
            field=campusflow_app.fields.EncryptedCharField(blank=True, help_text="Secret configured in the Razorpay dashboard's Webhooks section, used to verify webhook signatures.", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='cashfree_secret_key',
            field=campusflow_app.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mobikwik_secret_key',
            field=campusflow_app.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='paytm_merchant_key',
            field=campusflow_app.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='payu_merchant_salt',
            field=campusflow_app.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phonepe_salt_key',
            field=campusflow_app.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='razorpay_key_secret',
            field=campusflow_app.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
    ]
