# Generated by Django 6.0.6 on 2026-07-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0011_tenant_cashfree_app_id_tenant_cashfree_secret_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="tenant_type",
            field=models.CharField(
                choices=[("college", "College"), ("school", "School")],
                default="college",
                help_text="The type of institution: College or School",
                max_length=20,
            ),
        ),
    ]
