# Generated by Django 5.2.15 on 2026-07-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_tenant_billing_cycle_tenant_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_demo',
            field=models.BooleanField(default=False, help_text="Public sandbox tenant — password changes, email changes, outgoing mail, and destructive/config actions are blocked for every user in this tenant so a shared public demo can't be broken or hijacked."),
        ),
    ]
