# Generated by Django 6.0.6 on 2026-07-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Was "0011_tenant_cashfree_app_id_tenant_cashfree_secret_key_and_more"
        # — that migration was a fully duplicate parallel history of
        # 0009-0011+0013 in the other (applied) branch, deleted for the same
        # reason as in 0010_alter_invoice_bank_receipt.py above. This is the
        # one genuinely new field from that branch.
        ("tenants", "0014_alter_invoice_bank_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="tenant_type",
            field=models.CharField(
                choices=[("college", "College"), ("school", "School")],
                default="college",
                help_text="The type of institution: College or School",
                max_length=20,
            ),
        ),
    ]
